name: 'Admin theme'
description: 'Sets up Default Admin as the administrative (backend) theme.'
type: 'Themes'
install:
  - default_admin
  - block
config:
  # Leave existing blocks and menus as-is.
  strict: false
  import:
    system:
      - system.menu.account
      - system.menu.main
    default_admin:
      - block.block.default_admin_breadcrumbs
      - block.block.default_admin_content
      - block.block.default_admin_local_actions
      - block.block.default_admin_messages
      - block.block.default_admin_primary_local_tasks
      - block.block.default_admin_secondary_local_tasks
  actions:
    # Create this block dynamically so as not to conflict with the block created
    # by block_theme_initialize() when Default Admin is installed.
    block.block.default_admin_page_title:
      createIfNotExists:
        theme: default_admin
        plugin: page_title_block
        settings:
          id: page_title_block
          label: 'Page title'
          label_display: '0'
          provider: core
      setRegion: header
      setStatus: true
      setWeight: -30
    system.theme:
      simpleConfigUpdate:
        admin: default_admin
