<?php

/**
 * @file
 * Mock module for testing simpletest.
 */

/**
 * Implements hook_simpletest_alter().
 *
 * This hook is deprecated and should trigger a deprecation error when invoked.
 */
function simpletest_deprecation_test_simpletest_alter(&$groups) {
  // No-op.
}

/**
 * Implements hook_test_group_started().
 *
 * This hook is deprecated and should trigger a deprecation error when invoked.
 */
function simpletest_deprecation_test_test_group_started() {
  // No-op.
}

/**
 * Implements hook_test_group_finished().
 *
 * This hook is deprecated and should trigger a deprecation error when invoked.
 */
function simpletest_deprecation_test_test_group_finished() {
  // No-op.
}

/**
 * Implements hook_test_finished().
 *
 * This hook is deprecated and should trigger a deprecation error when invoked.
 */
function simpletest_deprecation_test_test_finished($results) {
  // No-op.
}
