/**
* DO NOT EDIT THIS FILE.
* All changes should be applied to ./modules/responsive_image/js/responsive_image.ajax.es6.js
* See the following change record for more information,
* https://www.drupal.org/node/2873849
* @preserve
**/

(function (Drupal) {

  'use strict';

  Drupal.behaviors.responsiveImageAJAX = {
    attach: function attach() {
      if (window.picturefill) {
        window.picturefill();
      }
    }
  };
})(Drupal);