<?php

namespace Drupal\system\Controller;

use Drupal\Core\Cache\CacheableJsonResponse;
use Drupal\Core\DependencyInjection\ContainerInjectionInterface;
use Drupal\Core\Theme\ManifestGeneratorInterface;
use Drupal\Core\Theme\ThemeManagerInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Returns response for the system manifest route.
 */
class ManifestController implements ContainerInjectionInterface {

  /**
   * The manifest generator.
   *
   * @var \Drupal\Core\Theme\ManifestGeneratorInterface
   */
  protected $manifestGenerator;

  /**
   * The theme manager.
   *
   * @var \Drupal\Core\Theme\ThemeManagerInterface
   */
  protected $themeManager;

  /**
   * ManifestController constructor.
   *
   * @param \Drupal\Core\Theme\ManifestGeneratorInterface $manifestGenerator
   *   The manifest generator.
   * @param \Drupal\Core\Theme\ThemeManagerInterface $themeManager
   *   The theme manager.
   */
  public function __construct(ManifestGeneratorInterface $manifestGenerator, ThemeManagerInterface $themeManager) {
    $this->manifestGenerator = $manifestGenerator;
    $this->themeManager = $themeManager;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('theme.manifest_generator'),
      $container->get('theme.manager')
    );
  }

  /**
   * Returns JSON data for the manifest.json file.
   *
   * The actual data is generated by \Drupal\Core\Theme\ManifestGenerator.
   *
   * @return \Drupal\Core\Cache\CacheableJsonResponse
   *   The JSON response.
   */
  public function manifest() : CacheableJsonResponse {
    $themeName = $this->themeManager->getActiveTheme()->getName();
    $manifestData = $this->manifestGenerator->generateManifest($themeName);

    $response = new CacheableJsonResponse();
    $response->addCacheableDependency($manifestData);
    $response->setData($manifestData->toArray());
    return $response;
  }

}
