<?php
// $Id: node_test_exception.module,v 1.4 2010/01/09 21:54:01 webchick Exp $

/**
 * @file
 * Dummy module implementing node related hooks to test API interaction with
 * the Node module.
 */

/**
 * Implements hook_node_insert().
 */
function node_test_exception_node_insert($node) {
  if ($node->title == 'testing_transaction_exception') {
    throw new Exception('Test exception for rollback.');
  }
}
