<?php
// $Id$

include_once "includes/common.inc";

function status($message) {
  if ($message) {
    return "<b>Status:</b> $message<hr />\n";
  }
}

function admin_help($section) {
  $output = "";

  switch ($section) {
    case "admin/system/modules":
      $output .= "Handles the administration pages.";
      break;
    case "admin":
      $output .= "Welcome to the administration section. Below are the most recent system events.  To get started please choose an item in the left column. If there is an arrow it will expand into a submenu. To jump up a level use the link,bread crumbs, above this block of text. To return to the home page click on the site name, and to go to Drupal's home page click on Druplicon, the drop on to the right.";
      break;
    case "admin":
      $output = "This is a complete overview of the site administration page.";
      break;
  }
  return t($output);
}

function admin_system($field){
  $output = "";
  if ($field == "description") {
    $output = admin_help("admin/system/modules");
  }

  return $output;
}

function admin_link($type) {
  if ($type == "system" && user_access("access administration pages")) {
    menu("admin", t("administer %a", array("%a" => variable_get("site_name", "drupal"))) , NULL, NULL, 9);
    menu("admin/overview", "sitemap", "overview_callback", admin_help("admin/overview"), 8);
  }
}

function overview_callback() {
  return menu_map();
}

function admin_admin() {
  return menu_map();
}


function admin_page() {
  if (user_access("access administration pages")) {
    if (!isset($GLOBALS["_gmenu"])) {
      menu_build("system");
    }
    if ($help = menu_help()) {
      $contents = "<small>$help</small><hr />";
    }
    if (arg(1)) {
      $contents .= menu_execute_action();
    }
    else {
      $contents.= watchdog_overview("actions");
      $title = t("System messages");
    }

    $breadcrumb = menu_path();
    array_pop($breadcrumb);
    $title = menu_title();

    theme("header");
    theme("breadcrumb", $breadcrumb);
    theme("box", $title, $contents);
    theme("footer");
  }
  else {
    theme("header");
    theme("box", t("Access denied"), message_access());
    theme("footer");
  }
}

?>
