<?php
// $Id$

/**
 * Implementation of hook_help().
 */
function admin_help($section) {
  switch ($section) {
    case "admin/system/modules#description":
      return t("Handles the administration pages.");
    case "admin":
      return t("Welcome to the administration section. Below are the most recent system events.");
    case "admin/overview":
      return t("This is a complete overview of the site administration page.");
  }
}

/**
 * Implementation of hook_link().
 */
function admin_link($type) {
  if ($type == 'system') {
    menu('admin', t('administer'), user_access('access administration pages') ? 'admin_admin' : MENU_DENIED, 9);
  }
}

/**
 * Menu callback. Provides an overview to serve as the main page of the
 * administration section.
 */
function admin_admin() {
  print theme("page", watchdog_overview("actions"));
}

?>
