<?php

/**
 * @file
 * Module file for workflow_type_test.
 */

declare(strict_types=1);

/**
 * Sets the type plugin definitions override and clear the cache.
 *
 * @param array $definitions
 *   Definitions to set.
 */
function workflow_type_test_set_definitions($definitions) {
  \Drupal::state()->set('workflow_type_test.plugin_definitions', $definitions);
  \Drupal::service('plugin.manager.workflows.type')->clearCachedDefinitions();
}
