<?php

/**
 * @file
 * Helper module for Ajax framework tests.
 */

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\AlertCommand;
use Drupal\Core\Ajax\OpenDialogCommand;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Drupal\Core\Ajax\CloseDialogCommand;
use Drupal\Core\Url;

/**
 * Menu callback: Returns AJAX element with #error property set.
 *
 * @deprecated \Drupal\ajax_test\Controller\AjaxTestController::renderError()
 */
function ajax_test_error() {
  $message = '';
  $query = \Drupal::request()->query;
  if ($query->has('message')) {
    $message = $query->get('message');
  }
  $response = new AjaxResponse();
  $response->addCommand(new AlertCommand($message));
  return $response;
}

/**
 * Returns example content for dialog tests.
 */
function ajax_test_dialog_contents() {
  // This is a regular render array; the keys do not have special meaning.
  $content = array(
    '#title' => 'AJAX Dialog contents',
    'content' => array(
      '#markup' => 'Example message',
    ),
    'cancel' => array(
      '#type' => 'link',
      '#title' => 'Cancel',
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => array(
        // This is a special class to which JavaScript assigns dialog closing
        // behavior.
        'class' => array('dialog-cancel'),
      ),
    ),
  );

  return $content;
}

/**
 * Menu callback: Close the ajax dialog.
 *
 * @deprecated \Drupal\ajax_test\Controller\AjaxTestController::dialogClose()
 */
function ajax_test_dialog_close() {
  $response = new AjaxResponse();
  $response->addCommand(new CloseDialogCommand('#ajax-test-dialog-wrapper-1'));
  return $response;
}
