<?php

/**
 * @file
 * Helper module for the Media oEmbed tests.
 */

declare(strict_types=1);

/**
 * Implements hook_preprocess_media_oembed_iframe().
 */
function media_test_oembed_preprocess_media_oembed_iframe(array &$variables): void {
  if ($variables['resource']->getProvider()->getName() === 'YouTube') {
    $variables['media'] = str_replace('?feature=oembed', '?feature=oembed&pasta=rigatoni', (string) $variables['media']);
  }
  // @see \Drupal\Tests\media\Kernel\OEmbedIframeControllerTest
  $variables['#attached']['library'][] = 'media_test_oembed/frame';
  $variables['#cache']['tags'][] = 'yo_there';
}
