<?php

function import_help() {
 ?>
  <P>In Drupal you have <I>feeds</I> and <I>bundles</I>.   Feeds define news sources and bundles categoriz syndicated content by source, topic or any other heuristic.   Bundles provide a generalized way of creating composite feeds.  They allow you, for example, to combine various sport-related feeds into one bundle called "Sport".</P>
  <P>You can have several providers of news feeds.  You can add a feed by clicking the "add feed" link on the import administration pages.  Give the feed a name, supply the URI and a comma-separated list of attributes that you want to associate the feed with.  The update interval defines how often Drupal should go out to try and grab fresh content.  The expiration time defines how long syndicated content is kept in the database.  So set the update and expiration time and save your settings.  You have just defined your first feed.  If you have more feeds repeat as necessary.</P>
  <P>To verify whether your feed works, press "update items" at the overview page.  The number of items that have been sucessfully fetched, should then become visible in the third column of the feed overview.</P>
  <P>Now you have to define some bundles.  Bundles look for feeds that contain one of the keywords associated with the bundle and display those feeds together.  To define a bundle you have to give it a name and a comma-separated list of keywords just like this is the case for feeds.</P>
  <P>Your newly created bundle will now show up in the list of blocks that you can see at the block related administration pages.  There you can customize where and when your bundles will be displayed.</P>
 <?php
}

function import_conf_options() {
  $number = array(5 => 5, 10 => 10, 15 => 15, 20 => 20, 25 => 25, 30 => 30, 35 => 35, 40 => 40, 45 => 45, 50 => 50, 55 => 55, 60 => 60, 65 => 65, 70 => 70, 75 => 75, 80 => 80, 85 => 85, 90 => 90, 95 => 95, 100 => 100);
  $output .= form_select("Items per block", "import_block_limit", variable_get("import_block_limit", 15), $number, "The maximum number of items displayed in one block.");
  $output .= form_select("Items per page", "import_page_limit", variable_get("import_page_limit", 75), $number, "The maximum number of items displayed on one page.");
  return $output;
}

function import_perm() {
  return array("administer news feeds", "access news feeds");
}

function import_link($type) {
  if ($type == "admin" && user_access("administer news feeds")) {
    $links[] = "<a href=\"admin.php?mod=import\">news feeds</a>";
  }

  if ($type == "page" && user_access("access news feeds")) {
    $links[] = "<a href=\"module.php?mod=import\">". t("news feeds") ."</a>";
  }

  return $links ? $links : array();
}

function import_cron() {
  $result = db_query("SELECT * FROM feed WHERE timestamp + refresh < ". time());
  while ($feed = db_fetch_array($result)) {
    import_refresh($feed);
  }
}

function import_update() {
  $result = db_query("SELECT * FROM feed");
  while ($feed = db_fetch_array($result)) {
    import_refresh($feed);
  }
}

function import_format_item($item, $feed = 0) {
  global $theme, $user;

  if ($user->id && user_access("post blogs")) {
    $output .= "<a href=\"submit.php?mod=blog&type=import&id=$item->iid\"><img src=\"". $theme->image("blog.gif") ."\" border=\"0\" width=\"12\" height=\"16\" alt=\"" . t("Blog this item") . "\" /></a> ";
  }

  $output .= "<a href=\"". check_output($item->link) ."\" target=\"new\">". check_output($item->title) ."</a>";

  return $output ."<br />";
}

function import_bundle_block($attributes) {

  if ($attributes) {
    $keys = explode(",", $attributes);
    foreach ($keys as $key) $where[] = "attributes LIKE '%". trim($key) ."%'";

    $result = db_query("SELECT * FROM item WHERE ". implode(" OR ", $where) ." ORDER BY iid DESC LIMIT ". variable_get("import_block_limit", 15));
  }

  while ($item = db_fetch_object($result)) {
    $output .= import_format_item($item);
  }

  return $output;
}

function import_feed_block($feed) {
  $result = db_query("SELECT * FROM item WHERE fid = '$feed->fid' ORDER BY iid DESC LIMIT ". variable_get("import_block_limit", 15));

  while ($item = db_fetch_object($result)) {
    $output .= import_format_item($item);
  }

  return $output;
}

function import_block() {
  return array_merge(import_get_bundles(), import_get_feeds());
}

function import_get_bundles($attributes = 0) {
  $result = db_query("SELECT * FROM bundle ORDER BY title");

  $i = 0;
  while ($bundle = db_fetch_object($result)) {
    $block[$i][subject] = $bundle->title;
    $block[$i][content] = import_bundle_block($bundle->attributes) ."<p><div align=\"right\"><a href=\"module.php?mod=import&op=bundle&id=$bundle->bid\">". t("details") ."</a></div></p>";
    $block[$i][info] = "$bundle->title bundle";

    $i++;
  }

  return $block;
}

function import_get_feeds($attributes = 0) {
  $result = db_query("SELECT * FROM feed ORDER BY fid");

  $i = 0;
  while ($feed = db_fetch_object($result)) {
    $block[$i][subject] = $feed->title;
    $block[$i][content] = import_feed_block($feed) ."<p><div align=\"right\"><a href=\"module.php?mod=import&op=feed&id=$feed->fid\">". t("details") ."</a></div></p>";
    $block[$i][info] = "$feed->title feed";

    $i++;
  }

  return $block;
}

function import_remove($feed) {
  db_query("DELETE FROM item WHERE fid = '$feed[fid]'");
  return "feed '$feed[title]' reset.";
}

function import_refresh($feed) {

  /*
  ** Check whether the feed is properly configured:
  */

  if (!ereg("^http://|ftp://", $feed[url])) {
    watchdog("warning", "import: invalid or missing URL for '$feed[title]'");
  }

  /*
  ** Grab the headlines:
  */

  if ($fp = @fopen($feed[url], "r")) {
    // fetch data:
    while (!feof($fp)) {
      $data .= fgets($fp, 128);
    }
    fclose($fp);

    // initialize the translation table:
    $tt = array_flip(get_html_translation_table(HTML_ENTITIES));
    $tt["&apos;"] = "'";

    /*
    ** Remove expired items:
    */
    db_query("DELETE FROM item WHERE fid = '$feed[fid]' AND timestamp < ". (time() - $feed[uncache]));

    /*
    ** Remove unsupported tags or sub-elements:
    */

    $data = ereg_replace("<textinput([^s].*)</textinput>", "", $data);
    $data = ereg_replace("<image([^s].*)</image>", "", $data);

    /*
    ** Extract and process channel information:
    */

    $channel = ereg_replace("<item([^s].*)</item>", "", $data);

    eregi("<title>(.*)</title>", $channel, $title);
    eregi("<link>(.*)</link>", $channel, $link);
    eregi("<description>(.*)</description>", $channel, $description);

    db_query("UPDATE feed SET timestamp = '". time() ."', link = '". check_input($link[1]) ."', description = '". check_input($description[1]) ."' WHERE fid = '". $feed[fid] ."'");

    /*
    ** Extract and process individual items:
    */

    eregi("<item([^s].*)</item>", $data, $data);
    // print "<pre>". htmlentities($data[0]) ."</pre>";

    $items = array_reverse(explode("</item>", $data[0]));

    foreach ($items as $item) {
      unset($title, $link, $author, $description);

      $t = eregi("<title>(.*)</title>", $item, $title);
      $l = eregi("<link>(.*)</link>", $item, $link);
      $a = eregi("<author>(.*)</author>", $item, $author);
      $d = eregi("<description>(.*)</description>", $item, $description);

      if ($t || $l || $a || $d) {

        /*
        ** Strip invalid tags and provide default values (if required):
        */

        $title = strip_tags(strtr($title[1] ? $title[1] : substr(strip_tags(strtr($description[1], $tt)), 0, 30), $tt));
        $link = $link[1] ? $link[1] : $feed[link];
        $description = strtr($description[1], $tt);

        // print "<pre>title = ". htmlentities($title) ."\n\ndescription = ". htmlentities($description) ."\n\nlink = ". htmlentities($link) ."</pre><hr />";

        /*
        ** Save this item:
        */

        import_save_item(array(fid => $feed[fid], title => $title, link => $link, author => $author[1], description => $description, attributes => $feed[attributes]));
      }
    }
  }
  else {
    watchdog("warning", "import: failed to syndicate from '$feed[title]'". ($errstr ? ": $errstr" : ""));
  }

  return "feed '$feed[title]' updated.";
}

function import_save_item($edit) {
  if ($edit[iid] && $edit[title]) {
    db_query("UPDATE item SET title = '". check_input($edit[title]) ."', link = '". check_input($edit[link]) ."', author = '". check_input($edit[author]) ."', description = '". check_input($edit[description]) ."', attributes = '". check_input($edit[attributes]) ."' WHERE iid = '$edit[iid]'");
  }
  else if ($edit[iid]) {
    db_query("DELETE FROM item WHERE iid = '". check_input($edit[iid]) ."'");
  }
  else if ($edit[title] && $edit[link]) {
    if (!db_fetch_object(db_query("SELECT iid FROM item WHERE title = '". check_input($edit[title]) ."' AND link = '". check_input($edit[link]) ."' AND description = '". check_input($edit[description]) ."'"))) {
      db_query("INSERT INTO item (fid, title, link, author, description, attributes, timestamp) VALUES ('". check_input($edit[fid]) ."', '". check_input($edit[title]) ."', '". check_input($edit[link]) ."', '". check_input($edit[author]) ."', '". check_input($edit[description]) ."', '". check_input($edit[attributes]) ."', '". time() ."')");
    }
  }
}

function import_form_bundle($edit = array()) {
  global $REQUEST_URI;

  $form .= form_textfield("Title", "title", $edit[title], 50, 64, "The name of the bundle.");
  $form .= form_textfield("Attributes", "attributes", $edit[attributes], 50, 128, "A comma-seperated list of keywords describing the bundle.");

  $form .= form_submit("Submit");

  if ($edit[bid]) {
    $form .= form_submit(t("Delete"));
    $form .= form_hidden("bid", $edit[bid]);
  }

  return form($REQUEST_URI, $form);
}

function import_save_bundle($edit) {
  if ($edit[bid] && $edit[title]) {
    db_query("UPDATE bundle SET title = '". check_input($edit[title]) ."', attributes = '". check_input($edit[attributes]) ."' WHERE bid = '". check_input($edit[bid]) ."'");
  }
  else if ($edit[bid]) {
    db_query("DELETE FROM bundle WHERE bid = '". check_input($edit[bid]) ."'");
  }
  else if ($edit[title]) {
    db_query("INSERT INTO bundle (title, attributes) VALUES ('". check_input($edit[title]) ."', '". check_input($edit[attributes]) ."')");
  }

  module_rehash_blocks("import");
}

function import_form_feed($edit = array()) {
  global $REQUEST_URI;

  $period = array(900 => format_interval(900), 1800 => format_interval(1800), 3600 => format_interval(3600), 7200 => format_interval(7200), 10800 => format_interval(10800), 21600 => format_interval(21600), 32400 => format_interval(32400), 43200 => format_interval(43200), 64800 => format_interval(64800), 86400 => format_interval(86400), 172800 => format_interval(172800), 259200 => format_interval(259200), 604800 => format_interval(604800), 1209600 => format_interval(1209600), 2419200 => format_interval(2419200));

  if ($edit[refresh] == "") $edit[refresh] = 3600;
  if ($edit[uncache] == "") $edit[uncache] = 2419200;

  $form .= form_textfield("Title", "title", $edit[title], 50, 64, "The name of the feed; typically the name of the website you syndicate content from.");
  $form .= form_textfield("Url", "url", $edit[url], 50, 128, "The fully-qualified URL of the feed.");
  $form .= form_textfield("Attributes", "attributes", $edit[attributes], 50, 128, "A comma-seperated list of keywords describing the feed.");
  $form .= form_select("Update interval", "refresh", $edit[refresh], $period, "The refresh interval indicating how often you want to update this feed.  Requires crontab.");
  $form .= form_select("Expiration time", "uncache", $edit[uncache], $period, "The time cached items should be kept.  Older items will be automatically discarded.  Requires crontab.");

  $form .= form_submit("Submit");

  if ($edit[fid]) {
    $form .= form_submit(t("Delete"));
    $form .= form_hidden("fid", $edit[fid]);
  }

  return form($REQUEST_URI, $form);
}

function import_save_feed($edit) {
  if ($edit[fid] && $edit[title]) {
    db_query("UPDATE feed SET title = '". check_input($edit[title]) ."', url = '". check_input($edit[url]) ."', attributes = '". check_input($edit[attributes]) ."', refresh = '". check_input($edit[refresh]) ."', uncache = '". check_input($edit[uncache]) ."' WHERE fid = '". check_input($edit[fid]) ."'");
    db_query("DELETE FROM item WHERE fid = '". check_input($edit[fid]) ."'");
  }
  else if ($edit[fid]) {
    db_query("DELETE FROM feed WHERE fid = '". check_input($edit[fid]) ."'");
    db_query("DELETE FROM item WHERE fid = '". check_input($edit[fid]) ."'");
  }
  else if ($edit[title]) {
    db_query("INSERT INTO feed (title, url, attributes, refresh, uncache) VALUES ('". check_input($edit[title]) ."', '". check_input($edit[url]) ."', '". check_input($edit[attributes]) ."', '". check_input($edit[refresh]) ."', '". check_input($edit[uncache]) ."')");
  }
}

function import_save_attributes($edit) {
  foreach($edit as $iid => $value) {
    db_query("UPDATE item SET attributes = '". check_input($value) ."' WHERE iid = '". check_input($iid) ."'");
  }
  return "attributes has been saved";
}

function import_get_feed($fid) {
  return db_fetch_array(db_query("SELECT * FROM feed WHERE fid = '". check_input($fid) ."'"));
}

function import_get_bundle($bid) {
  return db_fetch_array(db_query("SELECT * FROM bundle WHERE bid = '". check_input($bid) ."'"));
}

function import_view() {
  $result = db_query("SELECT f.*, COUNT(i.iid) AS items FROM feed f LEFT JOIN item i ON f.fid = i.fid GROUP BY f.fid ORDER BY f.title");

  $output .= "<h3>Feed overview</h3>";
  $output .= "<table border=\"1\" cellpadding=\"2\" cellspacing=\"2\">\n";
  $output .= " <tr><th>title</th><th>attributes</th><th>items</th><th>last update</th><th>next update</th><th colspan=\"3\">operations</th></tr>\n";
  while ($feed = db_fetch_object($result)) {
    $output .= " <tr><td>". check_output($feed->title) ."</td><td>". check_output($feed->attributes) ."</td><td>". format_plural($feed->items, "item", "items") ."</td><td>". ($feed->timestamp ? format_interval(time() - $feed->timestamp) ." ago" : "never") ."</td><td>". ($feed->timestamp ? format_interval($feed->timestamp + $feed->refresh - time()) ." left" : "never") ."</td><td><a href=\"admin.php?mod=import&type=feed&op=edit&id=$feed->fid\">edit feed</a></td><td><a href=\"admin.php?mod=import&type=feed&op=remove&id=$feed->fid\">remove items</a></td><td><a href=\"admin.php?mod=import&type=feed&op=update&id=$feed->fid\">update items</a></td></tr>\n";
  }
  $output .= "</table>\n";

  $result = db_query("SELECT * FROM bundle ORDER BY title");

  $output .= "<h3>Bundle overview</h3>";
  $output .= "<table border=\"1\" cellpadding=\"2\" cellspacing=\"2\">\n";
  $output .= " <tr><th>title</th><th>attributes</th><th>operations</th></tr>\n";
  while ($bundle = db_fetch_object($result)) {
    $output .= " <tr><td>". check_output($bundle->title) ."</td><td>". check_output($bundle->attributes) ."</td><td><a href=\"admin.php?mod=import&type=bundle&op=edit&id=$bundle->bid\">edit bundle</a></td></tr>\n";
  }
  $output .= "</table>\n";

  return $output;
}

function import_fd_form() {
  global $REQUEST_URI;

  $form .= form_textfield("Feed directory file", "url", "http://", 64, 128, "The fully-qualified URL of the feed directory file.");
  $form .= form_submit("Collect feeds");

  return form($REQUEST_URI, $form);
}

function import_fd_collect($edit) {
  global $REQUEST_URI;

  set_time_limit(180);

  if ($fp = @fopen($edit[url], "r")) {
    // fetch data:
    while (!feof($fp)) {
      $data .= fgets($fp, 128);
    }
    fclose($fp);

    // initialize the translation table:
    $tt = array_flip(get_html_translation_table(HTML_ENTITIES));
    $tt["&apos;"] = "'";

    $items = explode("</channel>", $data);

    $output .= "<form action=\"$REQUEST_URI\" method=\"POST\">\n";

    foreach ($items as $item) {
      unset ($link, $title);

      // print "<pre>item = ". htmlentities($item) ."\n\n</pre>";

      eregi("<link>(.*)</link>", $item, $link);
      eregi("<title>(.*)</title>", $item, $title);

      $link = strip_tags(strtr($link[1], $tt));
      $title = strip_tags(strtr($title[1], $tt));

      // print "<b>title = $title, link = $link<br /></b>";
      if ($link && $link && !db_fetch_array(db_query("SELECT * FROM feed WHERE url = '". check_input($link) ."'"))) {
        $output .= "<input type=\"checkbox\" name=\"edit[$title]\" value=\"$link\"> ". strtr($title, $tt) ."<br />";
      }
    }

    $output .= "<input type=\"submit\" name=\"op\" value=\"Import feeds\" />\n";
    $output .= "</form>";

    return $output;
  }
  else {
    print status("failed to open '$edit[url]': $errstr.");
  }
}

function import_fd_import($edit) {
  if ($edit) {
    foreach ($edit as $title => $link) {
      import_save_feed(array("title" => $title, "url" => $link, "refresh" => 3600, "uncache" => 2419200));
    }
  }
}

function import_tag() {
  global $REQUEST_URI;

  $result = db_query("SELECT i.*, f.title AS feed FROM item i LEFT JOIN feed f ON i.fid = f.fid ORDER BY i.iid DESC LIMIT 50");

  $output .= "<form action=\"$REQUEST_URI\" method=\"post\">\n";
  $output .= "<table border=\"1\" cellpadding=\"2\" cellspacing=\"2\">\n";
  $output .= " <tr><th>time</th><th>feed</th><th>item</th></tr>\n";
  while ($item = db_fetch_object($result)) {
    $output .= " <tr><td valign=\"top\" nowrap=\"nowrap\">". format_date($item->timestamp, "custom", "m/d/y") ."<br />".format_date($item->timestamp, "custom", "H:i") ."</td><td align=\"center\" valign=\"top\" nowrap=\"nowrap\"><a href=\"admin.php?mod=import&type=feed&op=edit&id=$item->fid\">". check_output($item->feed) ."</a></td><td><a href=\"". check_output($item->link) ."\">". check_output($item->title) ."</a>". ($item->description ? "<br /><small><i>". check_output($item->description) ."</i></small>" : "") ."<br /><input type=\"text\" name=\"edit[$item->iid]\" value=\"". check_form($item->attributes) ."\" size=\"50\" /></td></tr>\n";
  }
  $output .= "</table>\n";
  $output .= "<input type=\"submit\" name=\"op\" value=\"Save attributes\" />\n";
  $output .= "</form>\n";

  return $output;
}

function import_admin() {
  global $op, $id, $type, $edit;

  if (user_access("administer news feeds")) {

    print "<small><a href=\"admin.php?mod=import&type=feed&op=add\">add new feed</a> | <a href=\"admin.php?mod=import&type=bundle&op=add\">add new bundle</a> | <a href=\"admin.php?mod=import&op=fd\">import feeds</a> | <a href=\"admin.php?mod=import&op=tag\">tag items</a> | <a href=\"admin.php?mod=import&op=view\">overview</a> | <a href=\"admin.php?mod=import&op=help\">help</a></small><hr />";

    switch($op) {
      case "help":
        print import_help();
        break;
      case "add":
        if ($type == "bundle")
          print import_form_bundle();
        else
          print import_form_feed();
        break;
      case "edit":
        if ($type == "bundle")
          print import_form_bundle(import_get_bundle($id));
        else
          print import_form_feed(import_get_feed($id));
        break;
      case "fd":
        print import_fd_form();
        break;
      case "Collect feeds":
        print import_fd_collect($edit);
        break;
      case "Import feeds":
        print import_fd_import($edit);
        print import_view();
        break;
      case "remove":
        print status(import_remove(import_get_feed($id)));
        print import_view();
        break;
      case "update":
        print status(import_refresh(import_get_feed($id)));
        print import_view();
        break;
      case "tag":
        print import_tag();
        break;
      case "Save attributes":
        print status(import_save_attributes($edit));
        print import_tag();
        break;
      case "Delete":
        $edit[title] = 0;
        // fall through:
      case "Submit":
        if ($type == "bundle")
          print status(import_save_bundle($edit));
        else
          print status(import_save_feed($edit));
        // fall through:
        print import_view();
        break;
      default:
        print import_view();
    }
  }
  else {
    print message_access();
  }
}

function import_page_info() {
  global $theme;

  $links[] = "<a href=\"module.php?mod=import\">". t("latest news") ."</a>";
  $links[] = "<a href=\"module.php?mod=import&op=feeds\">". t("news by source") ."</a>";
  $links[] = "<a href=\"module.php?mod=import&op=bundles\">". t("news by topic") ."</a>";
  $links[] = "<a href=\"module.php?mod=import&op=sources\">". t("news sources") ."</a>";

  return "<div align=\"center\">". $theme->links($links) ."</div>";
}

function import_page_last() {
  global $theme;

  $result = db_query("SELECT i.*, f.title AS ftitle, f.link AS flink FROM item i LEFT JOIN feed f ON i.fid = f.fid ORDER BY i.iid DESC LIMIT ". variable_get("import_page_limit", 75));

  $output .= "<table border=\"0\" cellpadding=\"4\" cellspacing=\"2\">";
  while ($item = db_fetch_object($result)) {
    $links[] = "<a href=\"submit.php?mod=blog&type=import&id=$item->iid\">". t("blog it") ."</a>";
    $links[] = "<a href=\"module.php?mod=import&op=feed&id=$item->fid\">". t("feed") ."</a>";

    if ($item->link) {
      $output .= "<tr><td>". format_url($item->link, $item->title) ." &middot; <a href=\"module.php?mod=import&op=feed&id=$item->fid\">$item->ftitle</a></td><td align=\"right\" nowrap=\"nowrap\" valign=\"top\">". $theme->links($links) ."</td></tr>\n";
    }
    if ($item->description) {
      $output .= "<tr><td colspan=\"2\"><div style=\"margin-left: 20px;\">". check_output($item->description) ."</div><br /></td></tr>";
    }

    unset($links);
  }
  $output .= "</table>\n";

  $theme->header();
  $theme->box(t("News feeds"), import_page_info());
  $theme->box(t("Latest news"), $output);
  $theme->footer();
}

function import_page_feed($fid) {
  global $theme;

  $feed = db_fetch_object(db_query("SELECT * FROM feed WHERE fid = '". check_input($fid) ."'"));

  $header .= "<p><b>". t("Website") .":</b><div style=\"margin-left: 20px;\">". format_url($feed->link) ."</div></p>";
  $header .= "<p><b>". t("Description") .":</b><div style=\"margin-left: 20px;\">". check_output($feed->description) ."</div></p>";
  $header .= "<p><b>". t("Last update") .":</b><div style=\"margin-left: 20px;\">". format_interval(time() - $feed->timestamp) ." ". t("ago") ."<a href=\"$feed->url\"><img src=\"". $theme->image("xml.gif") ."\" width=\"36\" height=\"14\" align=\"right\" border=\"0\" /></a><br /><br /></div></p>\n";

  $result = db_query("SELECT * FROM item WHERE fid = '". check_input($fid) ."' ORDER BY iid DESC LIMIT ". variable_get("import_page_limit", 75));

  $output .= "<table border=\"0\" cellpadding=\"4\" cellspacing=\"2\">";
  while ($item = db_fetch_object($result)) {
    $links[] = "<a href=\"submit.php?mod=blog&type=import&id=$item->iid\">". t("blog it") ."</a>";
    $links[] = "<a href=\"$item->link\">". t("visit") ."</a>";

    if ($item->link) {
      $output .= "<tr><td>". format_url($item->link, $item->title) ."</td><td align=\"right\" nowrap=\"nowrap\" valign=\"top\">". $theme->links($links) ."</td></tr>\n";
    }
    if ($item->description) {
      $output .= "<tr><td colspan=\"2\"><div style=\"margin-left: 20px;\">". check_output($item->description) ."</div><br /></td></tr>";
    }

    unset($links);
  }
  $output .= "</table>\n";

  $theme->header();
  $theme->box(check_output($feed->title), $header);
  $theme->box(t("Latest news"), $output);
  $theme->footer();
}

function import_page_bundle($bid) {
  global $theme;

  $bundle = db_fetch_object(db_query("SELECT * FROM bundle WHERE bid = '". check_input($bid) ."'"));

  $header .= "<p><b>". t("Website") .":</b><div style=\"margin-left: 20px;\">". format_url("module.php?mod=import&op=bundle&id=$bundle->bid") ."</div></p>";
  $header .= "<p><b>". t("Description") .":</b><div style=\"margin-left: 20px;\">". t("A composite news feed about") ." ". check_output($bundle->attributes) .".</div></p>";

  $keys = explode(",", $bundle->attributes);
  foreach ($keys as $key) $where[] = "i.attributes LIKE '%". trim($key) ."%'";
  $result = db_query("SELECT i.*, f.title AS ftitle, f.link AS flink FROM item i, feed f WHERE (". implode(" OR ", $where) .") AND i.fid = f.fid ORDER BY iid DESC LIMIT ". variable_get("import_page_limit", 75));

  $output .= "<table border=\"0\" cellpadding=\"4\" cellspacing=\"2\">";
  while ($item = db_fetch_object($result)) {
    $links[] = "<a href=\"submit.php?mod=blog&type=import&id=$item->iid\">". t("blog it") ."</a>";
    $links[] = "<a href=\"module.php?mod=import&op=feed&id=$item->fid\">". t("feed") ."</a>";
    $links[] = "<a href=\"$item->link\">". t("visit") ."</a>";

    if ($item->link) {
      $output .= "<tr><td>". format_url($item->link, $item->title) ." &middot; <a href=\"module.php?mod=import&op=feed&id=$item->fid\">$item->ftitle</a></td><td align=\"right\" nowrap=\"nowrap\" valign=\"top\">". $theme->links($links) ."</td></tr>\n";
    }
    if ($item->description) {
      $output .= "<tr><td colspan=\"2\"><div style=\"margin-left: 20px;\">". check_output($item->description) ."</div><br /></td></tr>";
    }

    unset($links);
  }
  $output .= "</table>\n";

  $theme->header();
  $theme->box(check_output($bundle->title), $header);
  $theme->box(t("Latest news"), $output);
  $theme->footer();

}

function import_page_sources() {
  global $theme;

  $result = db_query("SELECT * FROM feed ORDER BY title");

  while ($feed = db_fetch_object($result)) {
    $output .= format_url("module.php?mod=import&op=feed&id=$feed->fid", $feed->title);
    $output .= "<p><div style=\"margin-left: 20px;\">". check_output($feed->description) ."</div></p>";
  }

  $output .= "<a href=\"module.php?mod=import&op=fd\"><img src=\"". $theme->image("xml.gif") ."\" width=\"36\" height=\"14\" align=\"right\" border=\"0\" /></a><br />\n";

  $theme->header();
  $theme->box(t("News feeds"), import_page_info());
  $theme->box(t("News sources"), $output);
  $theme->footer();
}

function import_page_fd() {

  $result = db_query("SELECT * FROM feed ORDER BY title");

  $output .= "<?xml version=\"1.0\"?>\n\n";
  $output .= "<rssfeeds version=\"0.1\">\n\n";

  while ($feed = db_fetch_object($result)) {
    $output .= "<channel>\n";
    $output .= " <title>". htmlentities($feed->title) ."</title>\n";
    $output .= " <link>". htmlentities($feed->url) ."</link>\n";
    $output .= "</channel>\n\n";
  }

  $output .= "</rssfeeds>\n";


  print $output;
}

function import_page_bundles() {
  import_page_blocks(import_get_bundles());
}

function import_page_feeds() {
  import_page_blocks(import_get_feeds());
}

function import_page_blocks($blocks) {
  global $theme;

  $count = count($blocks);
  $items = ceil($count / 3);
  $c1 = min($items, $count);
  $c2 = min(2 * $items, $count);
  $c3 = $count;
  $i = 0;

  $theme->header();
  $theme->box(t("News feeds"), import_page_info());
  print "<table cellpadding=\"0\" cellspacing=\"5\" border=\"0\" width=\"100%\">\n";
  print " <tr>\n";
  print "  <td width=\"33%\" valign=\"top\">\n";
  for ($i; $i < $c1; $i++) $theme->box($blocks[$i]["subject"], $blocks[$i]["content"]);
  print "  </td>\n";
  print "  <td width=\"33%\" valign=\"top\">\n";
  for ($i; $i < $c2; $i++) $theme->box($blocks[$i]["subject"], $blocks[$i]["content"]);
  print "  </td>\n";
  print "  <td width=\"33%\" valign=\"top\">\n";
  for ($i; $i < $c3; $i++) $theme->box($blocks[$i]["subject"], $blocks[$i]["content"]);
  print "  </td>\n";
  print " </tr>\n";
  print "</table>\n";
  $theme->footer();
}

function import_page() {
  global $op, $id;

  if (user_access("access news feeds")) {
    switch($op) {
      case "feed":
        import_page_feed($id);
        break;
      case "bundle":
        import_page_bundle($id);
        break;
      case "feeds":
        import_page_feeds();
        break;
      case "bundles":
        import_page_bundles();
        break;
      case "sources":
        import_page_sources();
        break;
      case "fd":
        import_page_fd();
        break;
      default:
        import_page_last();
    }
  }
}

?>
