<?php

/**
 * @file
 * Support module for testing.
 */

declare(strict_types=1);

use Drupal\block_content\BlockContentInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function block_content_theme_suggestions_test_theme(): array {
  // It is necessary to explicitly register the template via hook_theme()
  // because it is added via a module, not a theme.
  return [
    'block__block_content__view_type__basic__full' => [
      'base hook' => 'block',
    ],
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function block_content_theme_suggestions_test_preprocess_block(&$variables): void {
  $block_content = $variables['elements']['content']['#block_content'] ?? NULL;
  if ($block_content instanceof BlockContentInterface) {
    $variables['label'] = $block_content->label();
  }
}

/**
 * Implements hook_node_view().
 */
function block_content_theme_suggestions_test_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, string $view_mode): void {
  // Provide content for the extra field in the form of a content block.
  if ($display->getComponent('block_content_extra_field_test')) {
    $entity_type_manager = \Drupal::entityTypeManager();
    // Load a block content entity with a known UUID created by test setup.
    // @see \Drupal\Tests\block_content\Functional\BlockContentThemeSuggestionsTest::setUp()
    $block_content = $entity_type_manager->getStorage('block_content')->loadByProperties([
      'uuid' => 'b22c881a-bcfd-4d0c-a41d-3573327705df',
    ]);
    $block_content = reset($block_content);
    $build['block_content_extra_field_test'] = $entity_type_manager->getViewBuilder('block_content')->view($block_content);
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function block_content_theme_suggestions_test_entity_extra_field_info(): array {
  // Add an extra field to the test bundle.
  $extra['node']['bundle_with_extra_field']['display']['block_content_extra_field_test'] = [
    'label' => t('Extra field'),
    'description' => t('Extra field description'),
    'weight' => 0,
  ];
  return $extra;
}
