/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal, drupalSettings) {
  Drupal.behaviors.activeLinks = {
    attach: function attach(context) {
      var path = drupalSettings.path;
      var queryString = JSON.stringify(path.currentQuery);
      var querySelector = path.currentQuery ? "[data-drupal-link-query='".concat(queryString, "']") : ':not([data-drupal-link-query])';
      var originalSelectors = [];
      var currentPathSelector = "[data-drupal-link-system-path=\"".concat(path.currentPath, "\"]");
      var queryMatchSelector = "[data-drupal-link-query='".concat(queryString, "']");
      var queryEmptySelector = "[data-drupal-link-query='']";
      var noQuerySelector = ':not([data-drupal-link-query])';

      if (path.currentQuery) {
        originalSelectors.push("".concat(currentPathSelector).concat(queryMatchSelector));
        originalSelectors.push("".concat(currentPathSelector).concat(queryEmptySelector));
        originalSelectors.push("".concat(currentPathSelector).concat(noQuerySelector));
      } else {
        originalSelectors.push("".concat(currentPathSelector).concat(queryEmptySelector));
        originalSelectors.push("".concat(currentPathSelector).concat(noQuerySelector));
      }

      var selectors;

      if (path.isFront) {
        if (path.currentQuery) {
          originalSelectors.push("[data-drupal-link-system-path=\"<front>\"]".concat(queryMatchSelector));
          originalSelectors.push("[data-drupal-link-system-path=\"<front>\"]".concat(queryEmptySelector));
          originalSelectors.push("[data-drupal-link-system-path=\"<front>\"]".concat(noQuerySelector));
        } else {
          originalSelectors.push("[data-drupal-link-system-path=\"<front>\"]".concat(queryEmptySelector));
          originalSelectors.push("[data-drupal-link-system-path=\"<front>\"]".concat(noQuerySelector));
        }
      }

      selectors = [].concat(originalSelectors.map(function (selector) {
        return "".concat(selector, ":not([hreflang])");
      }), originalSelectors.map(function (selector) {
        return "".concat(selector, "[hreflang=\"").concat(path.currentLanguage, "\"]");
      }));
      selectors = selectors.concat(selectors.map(function (current) {
        return current + querySelector;
      }));
      var activeLinks = context.querySelectorAll(selectors.join(','));
      var il = activeLinks.length;

      for (var i = 0; i < il; i++) {
        activeLinks[i].classList.add('is-active');
      }
    },
    detach: function detach(context, settings, trigger) {
      if (trigger === 'unload') {
        var activeLinks = context.querySelectorAll('[data-drupal-link-system-path].is-active');
        var il = activeLinks.length;

        for (var i = 0; i < il; i++) {
          activeLinks[i].classList.remove('is-active');
        }
      }
    }
  };
})(Drupal, drupalSettings);