<?php

/**
 * @file
 * Provides configuration import test helpers.
 */

/**
 * Implements hook_config_import_steps_alter().
 */
function config_import_test_config_import_steps_alter(&$sync_steps) {
  $sync_steps[] = '_config_import_test_config_import_steps_alter';
}

/**
 * Implements configuration synchronization step added by an alter for testing.
 *
 * @param array $context
 *   The batch context.
 */
function _config_import_test_config_import_steps_alter(&$context) {
  $GLOBALS['hook_config_test']['config_import_steps_alter'] = TRUE;
  $context['finished'] = 1;
  return;
}
