<?php

namespace Drupal\FunctionalJavascriptTests\Core;

use Drupal\Core\Url;
use Drupal\FunctionalJavascriptTests\WebDriverTestBase;

/**
 * Tests the addition of is-active classes via JavaScript.
 *
 * @group Javascript
 */
class IsActiveTest extends WebDriverTestBase {

  /**
   * {@inheritdoc}
   */
  protected static $modules = [
    'common_test',
    'system',
  ];

  /**
   * {@inheritdoc}
   */
  protected $defaultTheme = 'stark';

  /**
   * {@inheritdoc}
   */
  protected function setUp(): void {
    parent::setUp();

    $account = $this->drupalCreateUser();
    $this->drupalLogin($account);
  }

  /**
   * Tests that the is-active class is added in various scenarios.
   *
   * This largely replicates the tests in UrlTest::testActiveLinkAttributes(),
   * which test the server side versions of this functionality. This is testing
   * the client side version, which is what is used for authenticated users.
   */
  public function testIsActiveClassAdded() {
    $options_no_query = [];
    $options_query = [
      'query' => [
        'foo' => 'bar',
        'one' => 'two',
      ],
    ];
    $options_query_reverse = [
      'query' => [
        'one' => 'two',
        'foo' => 'bar',
      ],
    ];

    // Test #type link.
    $path = 'common-test/type-link-active-class';

    $this->drupalGet($path, $options_no_query);

    $this->assertSession()->elementExists('css', '[src^="/core/misc/active-link.js"]');
    $links = $this->xpath('//a[@href = :href and contains(@class, :class)]', [':href' => Url::fromRoute('common_test.l_active_class', [], $options_no_query)->toString(), ':class' => 'is-active']);
    $this->assertTrue(isset($links[0]), 'A link generated by the link generator to the current page is marked active.');

    $links = $this->xpath('//a[@href = :href and not(contains(@class, :class))]', [':href' => Url::fromRoute('common_test.l_active_class', [], $options_query)->toString(), ':class' => 'is-active']);
    $this->assertTrue(isset($links[0]), 'A link generated by the link generator to the current page with a query string when the current page has no query string is not marked active.');

    $this->drupalGet($path, $options_query);
    $this->assertSession()->elementExists('css', '[src^="/core/misc/active-link.js"]');
    $links = $this->xpath('//a[@href = :href and contains(@class, :class)]', [':href' => Url::fromRoute('common_test.l_active_class', [], $options_query)->toString(), ':class' => 'is-active']);
    $this->assertTrue(isset($links[0]), 'A link generated by the link generator to the current page with a query string that matches the current query string is marked active.');

    $links = $this->xpath('//a[@href = :href and contains(@class, :class)]', [':href' => Url::fromRoute('common_test.l_active_class', [], $options_query_reverse)->toString(), ':class' => 'is-active']);
    $this->assertTrue(isset($links[0]), 'A link generated by the link generator to the current page with a query string that has matching parameters to the current query string but in a different order is marked active.');

    $links = $this->xpath('//a[@href = :href and contains(@class, :class)]', [':href' => Url::fromRoute('common_test.l_active_class', [], $options_no_query)->toString(), ':class' => 'is-active']);
    $this->assertTrue(isset($links[0]), 'A link generated by the link generator to the current page without a query string when the current page has a query string is marked active.');

    $links = $this->xpath('//a[@href = :href and contains(@class, :class) and not(@data-drupal-link-query)]', [':href' => Url::fromRoute('common_test.l_active_class', [], $options_no_query)->toString(), ':class' => 'is-active']);
    $this->assertTrue(isset($links[0]), 'A link generated by the link generator without a query arg is marked active on a page with a query arg.');

    $this->drupalGet($path, ['query' => ['arg' => 'notexists']]);
    $this->assertSession()->elementExists('css', '[src^="/core/misc/active-link.js"]');
    $links = $this->xpath('//a[@href = :href and not(contains(@class, :class))]', [':href' => Url::fromRoute('common_test.l_active_class', [], $options_query)->toString(), ':class' => 'is-active']);
    $this->assertTrue(isset($links[0]), 'A link generated by the link generator to the current page with a query string that does not match the current page\'s query string is not marked active.');
  }

}
