<?php

/**
 * @file
 * Changes an exposed "type" filter from a multi-select to checkboxes.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\ExtensionFileIsConverted;

/**
 * Changes an exposed "type" filter from a multi-select to checkboxes.
 */
#[ExtensionFileIsConverted]
function views_test_checkboxes_theme_form_views_exposed_form_alter(&$form, FormStateInterface $form_state): void {
  if (isset($form['type'])) {
    $form['type']['#type'] = 'checkboxes';
  }
  if (isset($form['tid'])) {
    $form['tid']['#type'] = 'checkboxes';
  }
}
