<?php

/**
 * @file
 * Provides testing functionality.
 */

use Drupal\Component\Uuid\Php;
use Drupal\Core\Asset\AttachedAssets;
use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\Core\Database\Database;
use Drupal\Core\File\Exception\FileException;
use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StreamWrapper\PublicStream;
use Drupal\Core\Test\JUnitConverter;
use Drupal\Core\Test\PhpUnitTestRunner;
use Drupal\Core\Test\TestDatabase;
use Drupal\Core\Url;
use Drupal\simpletest\Form\SimpletestResultsForm;
use Drupal\simpletest\TestDiscovery;
use PHPUnit\Framework\TestCase;

/**
 * Implements hook_help().
 */
function simpletest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.simpletest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Testing module provides a framework for running automated tests. It can be used to verify a working state of Drupal before and after any code changes, or as a means for developers to write and execute tests for their modules. For more information, see the <a href=":simpletest">online documentation for the Testing module</a>.', [':simpletest' => 'https://www.drupal.org/documentation/modules/simpletest']) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Running tests') . '</dt>';
      $output .= '<dd><p>' . t('Visit the <a href=":admin-simpletest">Testing page</a> to display a list of available tests. For comprehensive testing, select <em>all</em> tests, or individually select tests for more targeted testing. Note that it might take several minutes for all tests to complete.', [':admin-simpletest' => Url::fromRoute('simpletest.test_form')->toString()]) . '</p>';
      $output .= '<p>' . t('After the tests run, a message will be displayed next to each test group indicating whether tests within it passed, failed, or had exceptions. A pass means that the test returned the expected results, while fail means that it did not. An exception normally indicates an error outside of the test, such as a PHP warning or notice. If there were failures or exceptions, the results will be expanded to show details, and the tests that had failures or exceptions will be indicated in red or pink rows. You can then use these results to refine your code and tests, until all tests pass.') . '</p></dd>';
      $output .= '</dl>';
      return $output;

    case 'simpletest.test_form':
      $output = t('Select the test(s) or test group(s) you would like to run, and click <em>Run tests</em>.');
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function simpletest_theme() {
  return [
    'simpletest_result_summary' => [
      'variables' => ['label' => NULL, 'items' => [], 'pass' => 0, 'fail' => 0, 'exception' => 0, 'debug' => 0],
    ],
  ];
}

/**
 * Implements hook_js_alter().
 */
function simpletest_js_alter(&$javascript, AttachedAssetsInterface $assets) {
  // Since SimpleTest is a special use case for the table select, stick the
  // SimpleTest JavaScript above the table select.
  $simpletest = drupal_get_path('module', 'simpletest') . '/simpletest.js';
  if (array_key_exists($simpletest, $javascript) && array_key_exists('core/misc/tableselect.js', $javascript)) {
    $javascript[$simpletest]['weight'] = $javascript['core/misc/tableselect.js']['weight'] - 1;
  }
}

/**
 * Prepares variables for simpletest result summary templates.
 *
 * Default template: simpletest-result-summary.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - label: An optional label to be rendered before the results.
 *   - ok: The overall group result pass or fail.
 *   - pass: The number of passes.
 *   - fail: The number of fails.
 *   - exception: The number of exceptions.
 *   - debug: The number of debug messages.
 */
function template_preprocess_simpletest_result_summary(&$variables) {
  $variables['items'] = _simpletest_build_summary_line($variables);
}

/**
 * Formats each test result type pluralized summary.
 *
 * @param array $summary
 *   A summary of the test results.
 *
 * @return array
 *   The pluralized test summary items.
 */
function _simpletest_build_summary_line($summary) {
  $translation = \Drupal::translation();
  $items['pass'] = $translation->formatPlural($summary['pass'], '1 pass', '@count passes');
  $items['fail'] = $translation->formatPlural($summary['fail'], '1 fail', '@count fails');
  $items['exception'] = $translation->formatPlural($summary['exception'], '1 exception', '@count exceptions');
  if ($summary['debug']) {
    $items['debug'] = $translation->formatPlural($summary['debug'], '1 debug message', '@count debug messages');
  }
  return $items;
}

/**
 * Formats test result summaries into a comma separated string for run-tests.sh.
 *
 * @param array $summary
 *   A summary of the test results.
 *
 * @return string
 *   A concatenated string of the formatted test results.
 */
function _simpletest_format_summary_line($summary) {
  $parts = _simpletest_build_summary_line($summary);
  return implode(', ', $parts);
}

/**
 * Runs tests.
 *
 * @param array[] $test_list
 *   List of tests to run. The top level is keyed by type of test, either
 *   'simpletest' or 'phpunit'. Under that is an array of class names to run.
 *
 * @return string
 *   The test ID.
 */
function simpletest_run_tests($test_list) {
  // We used to separate PHPUnit and Simpletest tests for a performance
  // optimization. In order to support backwards compatibility check if these
  // keys are set and create a single test list.
  // @todo https://www.drupal.org/node/2748967 Remove BC support in Drupal 9.
  if (isset($test_list['simpletest'])) {
    $test_list = array_merge($test_list, $test_list['simpletest']);
    unset($test_list['simpletest']);
  }
  if (isset($test_list['phpunit'])) {
    $test_list = array_merge($test_list, $test_list['phpunit']);
    unset($test_list['phpunit']);
  }

  $test_id = \Drupal::database()->insert('simpletest_test_id')
    ->useDefaults(['test_id'])
    ->execute();

  // Clear out the previous verbose files.
  try {
    \Drupal::service('file_system')->deleteRecursive('public://simpletest/verbose');
  }
  catch (FileException $e) {
    // Ignore failed deletes.
  }

  // Get the info for the first test being run.
  $first_test = reset($test_list);
  $info = TestDiscovery::getTestInfo($first_test);

  $batch = [
    'title' => t('Running tests'),
    'operations' => [
      ['_simpletest_batch_operation', [$test_list, $test_id]],
    ],
    'finished' => '_simpletest_batch_finished',
    'progress_message' => '',
    'library' => ['simpletest/drupal.simpletest'],
    'init_message' => t('Processing test @num of @max - %test.', ['%test' => $info['name'], '@num' => '1', '@max' => count($test_list)]),
  ];
  batch_set($batch);

  \Drupal::moduleHandler()->invokeAllDeprecated('Convert your test to a PHPUnit-based one and implement test listeners. See https://www.drupal.org/node/2934242', 'test_group_started');

  return $test_id;
}

/**
 * Executes PHPUnit tests and returns the results of the run.
 *
 * @param $test_id
 *   The current test ID.
 * @param $unescaped_test_classnames
 *   An array of test class names, including full namespaces, to be passed as
 *   a regular expression to PHPUnit's --filter option.
 * @param int $status
 *   (optional) The exit status code of the PHPUnit process will be assigned to
 *   this variable.
 *
 * @return array
 *   The parsed results of PHPUnit's JUnit XML output, in the format of
 *   {simpletest}'s schema.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *   \Drupal\Core\Test\PhpUnitTestRunner::runTests() instead.
 *
 * @see https://www.drupal.org/node/2948547
 */
function simpletest_run_phpunit_tests($test_id, array $unescaped_test_classnames, &$status = NULL) {
  $runner = PhpUnitTestRunner::create(\Drupal::getContainer());
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Test\PhpUnitTestRunner::runTests() instead. See https://www.drupal.org/node/2948547', E_USER_DEPRECATED);
  return $runner->runTests($test_id, $unescaped_test_classnames, $status);
}

/**
 * Inserts the parsed PHPUnit results into {simpletest}.
 *
 * @param array[] $phpunit_results
 *   An array of test results returned from simpletest_phpunit_xml_to_rows().
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *   \Drupal\Core\Test\TestDatabase::processPhpUnitResults() instead.
 *
 * @see https://www.drupal.org/node/3075252
 */
function simpletest_process_phpunit_results($phpunit_results) {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Test\TestDatabase::processPhpUnitResults() instead. See https://www.drupal.org/node/3075252', E_USER_DEPRECATED);
  TestDatabase::processPhpUnitResults($phpunit_results);
}

/**
 * Maps phpunit results to a data structure for batch messages and run-tests.sh.
 *
 * @param array $results
 *   The output from simpletest_run_phpunit_tests().
 *
 * @return array
 *   The test result summary. A row per test class.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *   \Drupal\Core\Test\PhpUnitTestRunner::summarizeResults() instead.
 *
 * @see https://www.drupal.org/node/2948547
 */
function simpletest_summarize_phpunit_result($results) {
  $runner = PhpUnitTestRunner::create(\Drupal::getContainer());
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Test\PhpUnitTestRunner::summarizeResults() instead. See https://www.drupal.org/node/2948547', E_USER_DEPRECATED);
  return $runner->summarizeResults($results);
}

/**
 * Returns the path to use for PHPUnit's --log-junit option.
 *
 * @param $test_id
 *   The current test ID.
 *
 * @return string
 *   Path to the PHPUnit XML file to use for the current $test_id.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *   \Drupal\Core\Test\PhpUnitTestRunner::xmlLogFilepath() instead.
 *
 * @see https://www.drupal.org/node/2948547
 */
function simpletest_phpunit_xml_filepath($test_id) {
  $runner = PhpUnitTestRunner::create(\Drupal::getContainer());
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Test\PhpUnitTestRunner::xmlLogFilepath() instead. See https://www.drupal.org/node/2948547', E_USER_DEPRECATED);
  return $runner->xmlLogFilePath($test_id);
}

/**
 * Returns the path to core's phpunit.xml.dist configuration file.
 *
 * @return string
 *   The path to core's phpunit.xml.dist configuration file.
 *
 * @deprecated in drupal:8.4.0 and is removed from drupal:9.0.0. PHPUnit test
 *   runners should change directory into core/ and then run the phpunit tool.
 *   See simpletest_phpunit_run_command() for an example.
 *
 * @see simpletest_phpunit_run_command()
 */
function simpletest_phpunit_configuration_filepath() {
  @trigger_error('The ' . __FUNCTION__ . ' function is deprecated since version 8.4.x and will be removed in 9.0.0.', E_USER_DEPRECATED);
  return \Drupal::root() . '/core/phpunit.xml.dist';
}

/**
 * Executes the PHPUnit command.
 *
 * @param array $unescaped_test_classnames
 *   An array of test class names, including full namespaces, to be passed as
 *   a regular expression to PHPUnit's --filter option.
 * @param string $phpunit_file
 *   A filepath to use for PHPUnit's --log-junit option.
 * @param int $status
 *   (optional) The exit status code of the PHPUnit process will be assigned to
 *   this variable.
 * @param string $output
 *   (optional) The output by running the phpunit command.
 *
 * @return string
 *   The results as returned by exec().
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *   \Drupal\Core\Test\PhpUnitTestRunner::runCommand() instead.
 *
 * @see https://www.drupal.org/node/2948547
 */
function simpletest_phpunit_run_command(array $unescaped_test_classnames, $phpunit_file, &$status = NULL, &$output = NULL) {
  $runner = PhpUnitTestRunner::create(\Drupal::getContainer());
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Test\PhpUnitTestRunner::runCommand() instead. See https://www.drupal.org/node/2948547', E_USER_DEPRECATED);
  return $runner->runCommand($unescaped_test_classnames, $phpunit_file, $status, $output);
}

/**
 * Returns the command to run PHPUnit.
 *
 * @return string
 *   The command that can be run through exec().
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *   \Drupal\Core\Test\PhpUnitTestRunner::phpUnitCommand() instead.
 *
 * @see https://www.drupal.org/node/2948547
 */
function simpletest_phpunit_command() {
  $runner = PhpUnitTestRunner::create(\Drupal::getContainer());
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Test\PhpUnitTestRunner::phpUnitCommand() instead. See https://www.drupal.org/node/2948547', E_USER_DEPRECATED);
  return $runner->phpUnitCommand();
}

/**
 * Implements callback_batch_operation().
 */
function _simpletest_batch_operation($test_list_init, $test_id, &$context) {
  \Drupal::service('test_discovery')->registerTestNamespaces();
  // Get working values.
  if (!isset($context['sandbox']['max'])) {
    // First iteration: initialize working values.
    $test_list = $test_list_init;
    $context['sandbox']['max'] = count($test_list);
    $test_results = ['#pass' => 0, '#fail' => 0, '#exception' => 0, '#debug' => 0];
  }
  else {
    // Nth iteration: get the current values where we last stored them.
    $test_list = $context['sandbox']['tests'];
    $test_results = $context['sandbox']['test_results'];
  }
  $max = $context['sandbox']['max'];

  // Perform the next test.
  $test_class = array_shift($test_list);
  if (is_subclass_of($test_class, TestCase::class)) {
    $runner = PhpUnitTestRunner::create(\Drupal::getContainer());
    $phpunit_results = $runner->runTests($test_id, [$test_class]);
    TestDatabase::processPhpUnitResults($phpunit_results);
    $test_results[$test_class] = simpletest_summarize_phpunit_result($phpunit_results)[$test_class];
  }
  else {
    $test = new $test_class($test_id);
    $test->run();
    \Drupal::moduleHandler()->invokeAllDeprecated('Convert your test to a PHPUnit-based one and implement test listeners. See https://www.drupal.org/node/2934242', 'test_finished', [$test->results]);
    $test_results[$test_class] = $test->results;
  }
  $size = count($test_list);
  $info = TestDiscovery::getTestInfo($test_class);

  // Gather results and compose the report.
  foreach ($test_results[$test_class] as $key => $value) {
    $test_results[$key] += $value;
  }
  $test_results[$test_class]['#name'] = $info['name'];
  $items = [];
  foreach (Element::children($test_results) as $class) {
    $class_test_result = $test_results[$class] + [
      '#theme' => 'simpletest_result_summary',
      '#label' => t($test_results[$class]['#name'] . ':'),
    ];
    array_unshift($items, \Drupal::service('renderer')->render($class_test_result));
  }
  $context['message'] = t('Processed test @num of @max - %test.', ['%test' => $info['name'], '@num' => $max - $size, '@max' => $max]);
  $overall_results = $test_results + [
    '#theme' => 'simpletest_result_summary',
    '#label' => t('Overall results:'),
  ];
  $context['message'] .= \Drupal::service('renderer')->render($overall_results);

  $item_list = [
    '#theme' => 'item_list',
    '#items' => $items,
  ];
  $context['message'] .= \Drupal::service('renderer')->render($item_list);

  // Save working values for the next iteration.
  $context['sandbox']['tests'] = $test_list;
  $context['sandbox']['test_results'] = $test_results;
  // The test_id is the only thing we need to save for the report page.
  $context['results']['test_id'] = $test_id;

  // Multistep processing: report progress.
  $context['finished'] = 1 - $size / $max;
}

/**
 * Implements callback_batch_finished().
 */
function _simpletest_batch_finished($success, $results, $operations, $elapsed) {
  if ($success) {
    \Drupal::messenger()->addStatus(t('The test run finished in @elapsed.', ['@elapsed' => $elapsed]));
  }
  else {
    // Use the test_id passed as a parameter to _simpletest_batch_operation().
    $test_id = $operations[0][1][1];

    // Retrieve the last database prefix used for testing and the last test
    // class that was run from. Use the information to read the lgo file
    // in case any fatal errors caused the test to crash.
    $last_test = TestDatabase::lastTestGet($test_id);
    (new TestDatabase($last_test['last_prefix']))->logRead($test_id, $last_test['test_class']);

    \Drupal::messenger()->addError(t('The test run did not successfully finish.'));
    \Drupal::messenger()->addWarning(t('Use the <em>Clean environment</em> button to clean-up temporary files and tables.'));
  }
  \Drupal::moduleHandler()->invokeAllDeprecated('Convert your test to a PHPUnit-based one and implement test listeners. See https://www.drupal.org/node/2934242', 'test_group_finished');
}

/**
 * Get information about the last test that ran given a test ID.
 *
 * @param $test_id
 *   The test ID to get the last test from.
 * @return array
 *   Array containing the last database prefix used and the last test class
 *   that ran.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *   \Drupal\Core\Test\TestDatabase::lastTestGet() instead.
 *
 * @see https://www.drupal.org/node/3075252
 */
function simpletest_last_test_get($test_id) {
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Test\TestDatabase::lastTestGet() instead. See https://www.drupal.org/node/3075252', E_USER_DEPRECATED);
  return array_values(TestDatabase::lastTestGet($test_id));
}

/**
 * Reads the error log and reports any errors as assertion failures.
 *
 * The errors in the log should only be fatal errors since any other errors
 * will have been recorded by the error handler.
 *
 * @param $test_id
 *   The test ID to which the log relates.
 * @param $database_prefix
 *   The database prefix to which the log relates.
 * @param $test_class
 *   The test class to which the log relates.
 *
 * @return bool
 *   Whether any fatal errors were found.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *   \Drupal\Core\Test\TestDatabase::logRead() instead.
 *
 * @see https://www.drupal.org/node/3075252
 */
function simpletest_log_read($test_id, $database_prefix, $test_class) {
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Test\TestDatabase::logRead() instead. See https://www.drupal.org/node/3075252', E_USER_DEPRECATED);
  $test_db = new TestDatabase($database_prefix);
  return $test_db->logRead($test_id, $test_class);
}

/**
 * Store an assertion from outside the testing context.
 *
 * This is useful for inserting assertions that can only be recorded after
 * the test case has been destroyed, such as PHP fatal errors. The caller
 * information is not automatically gathered since the caller is most likely
 * inserting the assertion on behalf of other code. In all other respects
 * the method behaves just like \Drupal\simpletest\TestBase::assert() in terms
 * of storing the assertion.
 *
 * @param string $test_id
 *   The test ID to which the assertion relates.
 * @param string $test_class
 *   The test class to store an assertion for.
 * @param bool|string $status
 *   A boolean or a string of 'pass' or 'fail'. TRUE means 'pass'.
 * @param string $message
 *   The assertion message.
 * @param string $group
 *   The assertion message group.
 * @param array $caller
 *   The an array containing the keys 'file' and 'line' that represent the file
 *   and line number of that file that is responsible for the assertion.
 *
 * @return
 *   Message ID of the stored assertion.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *   \Drupal\Core\Test\TestDatabase::insertAssert() instead.
 *
 * @see https://www.drupal.org/node/3075252
 */
function simpletest_insert_assert($test_id, $test_class, $status, $message = '', $group = 'Other', array $caller = []) {
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Test\TestDatabase::insertAssert() instead. See https://www.drupal.org/node/3075252', E_USER_DEPRECATED);
  TestDatabase::insertAssert($test_id, $test_class, $status, $message, $group, $caller);
}

/**
 * Gets a list of all of the tests provided by the system.
 *
 * The list of test classes is loaded by searching the designated directory for
 * each module for files matching the PSR-4 standard. Once loaded the test list
 * is cached and stored in a static variable.
 *
 * @param string $extension
 *   (optional) The name of an extension to limit discovery to; e.g., 'node'.
 * @param string[] $types
 *   An array of included test types.
 *
 * @return array[]
 *   An array of tests keyed with the groups, and then keyed by test classes.
 *   For example:
 *   @code
 *     $groups['Block'] => array(
 *       'BlockTestCase' => array(
 *         'name' => 'Block functionality',
 *         'description' => 'Add, edit and delete custom block.',
 *         'group' => 'Block',
 *       ),
 *     );
 *   @endcode
 *
 * @deprecated in drupal:8.3.0 and is removed from drupal:9.0.0. Use
 *   \Drupal::service('test_discovery')->getTestClasses($extension, $types)
 *   instead.
 */
function simpletest_test_get_all($extension = NULL, array $types = []) {
  @trigger_error('The ' . __FUNCTION__ . ' function is deprecated in version 8.3.x and will be removed in 9.0.0. Use \Drupal::service(\'test_discovery\')->getTestClasses($extension, $types) instead.', E_USER_DEPRECATED);
  return \Drupal::service('test_discovery')->getTestClasses($extension, $types);
}

/**
 * Registers test namespaces of all extensions and core test classes.
 *
 * @deprecated in drupal:8.3.0 and is removed from drupal:9.0.0. Use
 *   \Drupal::service('test_discovery')->registerTestNamespaces() instead.
 */
function simpletest_classloader_register() {
  @trigger_error('The ' . __FUNCTION__ . ' function is deprecated in version 8.3.x and will be removed in 9.0.0. Use \Drupal::service(\'test_discovery\')->registerTestNamespaces() instead.', E_USER_DEPRECATED);
  \Drupal::service('test_discovery')->registerTestNamespaces();
}

/**
 * Generates a test file.
 *
 * @param string $filename
 *   The name of the file, including the path. The suffix '.txt' is appended to
 *   the supplied file name and the file is put into the public:// files
 *   directory.
 * @param int $width
 *   The number of characters on one line.
 * @param int $lines
 *   The number of lines in the file.
 * @param string $type
 *   (optional) The type, one of:
 *   - text: The generated file contains random ASCII characters.
 *   - binary: The generated file contains random characters whose codes are in
 *     the range of 0 to 31.
 *   - binary-text: The generated file contains random sequence of '0' and '1'
 *     values.
 *
 * @return string
 *   The name of the file, including the path.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *   \Drupal\Tests\TestFileCreationTrait::generateFile() instead.
 *
 * @see https://www.drupal.org/node/3077768
 */
function simpletest_generate_file($filename, $width, $lines, $type = 'binary-text') {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Tests\TestFileCreationTrait::generateFile() instead. See https://www.drupal.org/node/3077768', E_USER_DEPRECATED);
  $text = '';
  for ($i = 0; $i < $lines; $i++) {
    // Generate $width - 1 characters to leave space for the "\n" character.
    for ($j = 0; $j < $width - 1; $j++) {
      switch ($type) {
        case 'text':
          $text .= chr(rand(32, 126));
          break;
        case 'binary':
          $text .= chr(rand(0, 31));
          break;
        case 'binary-text':
        default:
          $text .= rand(0, 1);
          break;
      }
    }
    $text .= "\n";
  }

  // Create filename.
  file_put_contents('public://' . $filename . '.txt', $text);
  return $filename;
}

/**
 * Removes all temporary database tables and directories.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Access the
 *   environment_cleaner service and call its cleanEnvironment() method, or use
 *   \Drupal\Core\Test\EnvironmentCleaner::cleanEnvironment() instead.
 *
 * @see https://www.drupal.org/node/3076634
 */
function simpletest_clean_environment() {
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Access the environment_cleaner service and call its cleanEnvironment() method, or use \Drupal\Core\Test\EnvironmentCleaner::cleanEnvironment() instead.. See https://www.drupal.org/node/3076634', E_USER_DEPRECATED);
  /* @var $cleaner \Drupal\simpletest\EnvironmentCleanerService */
  $cleaner = \Drupal::service('environment_cleaner');
  $cleaner->cleanEnvironment();
}

/**
 * Removes prefixed tables from the database from crashed tests.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Access the
 *   environment_cleaner service and call its cleanDatabase() method, or use
 *   \Drupal\Core\Test\EnvironmentCleaner::cleanDatabase() instead.
 *
 * @see https://www.drupal.org/node/3076634
 */
function simpletest_clean_database() {
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Access the environment_cleaner service and call its cleanDatabase() method, or use \Drupal\Core\Test\EnvironmentCleaner::cleanDatabase() instead. See https://www.drupal.org/node/3076634', E_USER_DEPRECATED);
  /* @var $cleaner \Drupal\simpletest\EnvironmentCleanerService */
  $cleaner = \Drupal::service('environment_cleaner');
  $cleaner->cleanDatabase();
}

/**
 * Finds all leftover temporary directories and removes them.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Access the
 *   environment_cleaner service and call its cleanTemporaryDirectories()
 *   method, or use
 *   \Drupal\Core\Test\EnvironmentCleaner::cleanTemporaryDirectories() instead.
 *
 * @see https://www.drupal.org/node/3076634
 */
function simpletest_clean_temporary_directories() {
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Access the environment_cleaner service and call its cleanTemporaryDirectories() method, or use \Drupal\Core\Test\EnvironmentCleaner::cleanTemporaryDirectories() instead. See https://www.drupal.org/node/3076634', E_USER_DEPRECATED);
  /* @var $cleaner \Drupal\simpletest\EnvironmentCleanerService */
  $cleaner = \Drupal::service('environment_cleaner');
  $cleaner->cleanTemporaryDirectories();
}

/**
 * Clears the test result tables.
 *
 * @param $test_id
 *   Test ID to remove results for, or NULL to remove all results.
 *
 * @return int
 *   The number of results that were removed.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Access the
 *   environment_cleaner service and call its cleanResultsTable() method, or use
 *   \Drupal\Core\Test\EnvironmentCleaner::cleanResultsTable() instead.
 *
 * @see https://www.drupal.org/node/3076634
 */
function simpletest_clean_results_table($test_id = NULL) {
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Access the environment_cleaner service and call its cleanResultsTable() method, or use \Drupal\Core\Test\EnvironmentCleaner::cleanResultsTable() instead. See https://www.drupal.org/node/3076634', E_USER_DEPRECATED);
  $count = 0;
  if (\Drupal::config('simpletest.settings')->get('clear_results')) {
    /* @var $cleaner \Drupal\simpletest\EnvironmentCleanerService */
    $cleaner = \Drupal::service('environment_cleaner');
    $count = $cleaner->cleanResultsTable($test_id);
  }
  return $count;
}

/**
 * Converts PHPUnit's JUnit XML output to an array.
 *
 * @param $test_id
 *   The current test ID.
 * @param $phpunit_xml_file
 *   Path to the PHPUnit XML file.
 *
 * @return array[]|null
 *   The results as array of rows in a format that can be inserted into
 *   {simpletest}. If the phpunit_xml_file does not have any contents then the
 *   function will return NULL.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *   \Drupal\Core\Test\JUnitConverter::xmlToRows() instead.
 *
 * @see https://www.drupal.org/node/2948547
 */
function simpletest_phpunit_xml_to_rows($test_id, $phpunit_xml_file) {
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Test\JUnitConverter::xmlToRows() instead. See https://www.drupal.org/node/2948547', E_USER_DEPRECATED);
  return JUnitConverter::xmlToRows($test_id, $phpunit_xml_file) ?: NULL;
}

/**
 * Finds all test cases recursively from a test suite list.
 *
 * @param \SimpleXMLElement $element
 *   The PHPUnit xml to search for test cases.
 * @param \SimpleXMLElement $parent
 *   (Optional) The parent of the current element. Defaults to NULL.
 *
 * @return array
 *   A list of all test cases.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *   \Drupal\Core\Test\JUnitConverter::findTestCases() instead.
 *
 * @see https://www.drupal.org/node/2948547
 */
function simpletest_phpunit_find_testcases(\SimpleXMLElement $element, \SimpleXMLElement $parent = NULL) {
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Test\JUnitConverter::findTestCases() instead. See https://www.drupal.org/node/2948547', E_USER_DEPRECATED);
  return JUnitConverter::findTestCases($element, $parent);
}

/**
 * Converts a PHPUnit test case result to a {simpletest} result row.
 *
 * @param int $test_id
 *   The current test ID.
 * @param \SimpleXMLElement $test_case
 *   The PHPUnit test case represented as XML element.
 *
 * @return array
 *   An array containing the {simpletest} result row.
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use
 *  \Drupal\Core\Test\JUnitConverter::convertTestCaseToSimpletestRow() instead.
 *
 * @see https://www.drupal.org/node/2948547
 */
function simpletest_phpunit_testcase_to_row($test_id, \SimpleXMLElement $test_case) {
  @trigger_error(__FUNCTION__ . ' is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Test\JUnitConverter::convertTestCaseToSimpletestRow() instead. See https://www.drupal.org/node/2948547', E_USER_DEPRECATED);
  return JUnitConverter::convertTestCaseToSimpletestRow($test_id, $test_case);
}

/**
 * Display test results from run-tests.sh in a browser.
 *
 * @internal
 *   This function is only used by run-tests.sh
 *
 * @deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. This function
 *   supports the --browser option in this script. Use the --verbose option
 *   instead.
 *
 * @see https://www.drupal.org/node/3083549
 */
function _simpletest_run_tests_script_open_browser() {
  global $test_ids;

  try {
    $connection = Database::getConnection('default', 'test-runner');
    $results = $connection->select('simpletest')
      ->fields('simpletest')
      ->condition('test_id', $test_ids, 'IN')
      ->orderBy('test_class')
      ->orderBy('message_id')
      ->execute()
      ->fetchAll();
  }
  catch (Exception $e) {
    echo (string) $e;
    exit(SIMPLETEST_SCRIPT_EXIT_EXCEPTION);
  }

  // Get the results form.
  $form = [];
  SimpletestResultsForm::addResultForm($form, $results);

  // Get the assets to make the details element collapsible and theme the result
  // form.
  $assets = new AttachedAssets();
  $assets->setLibraries([
    'core/drupal.collapse',
    'system/admin',
    'simpletest/drupal.simpletest',
  ]);
  $resolver = \Drupal::service('asset.resolver');
  list($js_assets_header, $js_assets_footer) = $resolver->getJsAssets($assets, FALSE);
  $js_collection_renderer = \Drupal::service('asset.js.collection_renderer');
  $js_assets_header = $js_collection_renderer->render($js_assets_header);
  $js_assets_footer = $js_collection_renderer->render($js_assets_footer);
  $css_assets = \Drupal::service('asset.css.collection_renderer')->render($resolver->getCssAssets($assets, FALSE));

  // Make the html page to write to disk.
  $render_service = \Drupal::service('renderer');
  $html = '<head>' . $render_service->renderPlain($js_assets_header) . $render_service->renderPlain($css_assets) . '</head><body>' . $render_service->renderPlain($form) . $render_service->renderPlain($js_assets_footer) . '</body>';

  // Ensure we have assets verbose directory - tests with no verbose output will
  // not have created one.
  $directory = PublicStream::basePath() . '/simpletest/verbose';
  \Drupal::service('file_system')->prepareDirectory($directory, FileSystemInterface::CREATE_DIRECTORY | FileSystemInterface::MODIFY_PERMISSIONS);
  $php = new Php();
  $uuid = $php->generate();
  $filename = $directory . '/results-' . $uuid . '.html';
  $base_url = getenv('SIMPLETEST_BASE_URL');
  if (empty($base_url)) {
    simpletest_script_print_error("--browser needs argument --url.");
  }
  $url = $base_url . '/' . PublicStream::basePath() . '/simpletest/verbose/results-' . $uuid . '.html';
  file_put_contents($filename, $html);

  // See if we can find an OS helper to open URLs in default browser.
  $browser = FALSE;
  if (shell_exec('which xdg-open')) {
    $browser = 'xdg-open';
  }
  elseif (shell_exec('which open')) {
    $browser = 'open';
  }
  elseif (substr(PHP_OS, 0, 3) == 'WIN') {
    $browser = 'start';
  }

  if ($browser) {
    shell_exec($browser . ' ' . escapeshellarg($url));
  }
  else {
    // Can't find assets valid browser.
    print 'Open file://' . realpath($filename) . ' in your browser to see the verbose output.';
  }
}
