<?php

/**
 * @file
 */

use Drupal\contact\Hook\ContactFormHooks;
use Drupal\Core\Form\FormStateInterface;

/**
 * Form submission handler for \Drupal\user\ProfileForm.
 *
 * Saves the contact page setting.
 *
 * @deprecated in drupal:11.4.0 and is removed from drupal:12.0.0. Use
 *   \Drupal\contact\Hook\ContactFormHooks::profileFormSubmit() instead.
 *
 * @see https://www.drupal.org/node/3566774
 */
function contact_user_profile_form_submit($form, FormStateInterface $form_state): void {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:11.4.0 and is removed from drupal:12.0.0. Use \Drupal\contact\Hook\ContactFormHooks::profileFormSubmit() instead. See https://www.drupal.org/node/3566774', E_USER_DEPRECATED);
  \Drupal::service(ContactFormHooks::class)->profileFormSubmit($form, $form_state);
}

/**
 * Form submission handler for \Drupal\user\AccountSettingsForm.
 *
 * @deprecated in drupal:11.4.0 and is removed from drupal:12.0.0. Use
 *   \Drupal\contact\Hook\ContactFormHooks::userAdminSettingsSubmit instead.
 *
 * @see https://www.drupal.org/node/3566774
 */
function contact_form_user_admin_settings_submit($form, FormStateInterface $form_state): void {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:11.4.0 and is removed from drupal:12.0.0. Use \Drupal\contact\Hook\ContactFormHooks::userAdminSettingsSubmit instead. See https://www.drupal.org/node/3566774', E_USER_DEPRECATED);
  \Drupal::service(ContactFormHooks::class)->userAdminSettingsSubmit($form, $form_state);
}
