<?php
// $Id$

/**
 * @file
 * Test API interaction with the RDF module.
 */

/**
 * Implements hook_rdf_mapping().
 */
function rdf_test_rdf_mapping() {
  return array(
    array(
      'type' => 'test_entity',
      'bundle' => 'test_bundle',
      'mapping' => array(
        'rdftype' => array('sioc:Post'),
        'title' => array(
          'predicates' => array('dc:title'),
        ),
        'created' => array(
          'predicates' => array('dc:created'),
          'datatype' => 'xsd:dateTime',
          'callback' => 'date_iso8601',
        ),
        'uid' => array(
          'predicates' => array('sioc:has_creator', 'dc:creator'),
        ),
        'foobar' => array(
          'predicates' => array('foo:bar'),
        ),
      ),
    ),
    array(
      'type' => 'node',
      'bundle' => 'blog',
      'mapping' => array(
        'rdftype' => array('sioct:Weblog'),
      ),
    ),
  );
}
