import defaultConfig from './eslint.config.mjs';
import { defineConfig } from 'eslint/config';

export default defineConfig(defaultConfig, {
  linterOptions: {
    reportUnusedDisableDirectives: 'off',
  },
  rules: {
    'import/named': 'off',
    'import/namespace': 'off',
    'import/no-unresolved': 'off',

    'no-jquery/no-ajax': 'off',
    'no-jquery/no-ajax-events': 'error',
    'no-jquery/no-animate': 'error',
    'no-jquery/no-attr': 'off',
    'no-jquery/no-bind': 'error',
    'no-jquery/no-class': 'off',
    'no-jquery/no-clone': 'error',
    'no-jquery/no-closest': 'off',
    'no-jquery/no-css': 'error',
    'no-jquery/no-data': 'off',
    'no-jquery/no-deferred': 'off',
    'no-jquery/no-delegate': 'error',
    'no-jquery/no-each': 'off',
    'no-jquery/no-extend': 'off',
    'no-jquery/no-fade': 'off',
    'no-jquery/no-filter': 'off',
    'no-jquery/no-find': 'off',
    'no-jquery/no-global-eval': 'error',
    'no-jquery/no-grep': 'error',
    'no-jquery/no-has': 'off',
    'no-jquery/no-hide': 'off',
    'no-jquery/no-html': 'off',
    'no-jquery/no-in-array': 'off',
    'no-jquery/no-is-array': 'off',
    'no-jquery/no-is-function': 'error',
    'no-jquery/no-is': 'error',
    'no-jquery/no-load': 'error',
    'no-jquery/no-map': 'error',
    'no-jquery/no-merge': 'error',
    'no-jquery/no-param': 'error',
    'no-jquery/no-parent': 'off',
    'no-jquery/no-parents': 'off',
    'no-jquery/no-parse-html': 'error',
    'no-jquery/no-prop': 'off',
    'no-jquery/no-proxy': 'error',
    'no-jquery/no-ready': 'error',
    'no-jquery/no-serialize': 'error',
    'no-jquery/no-show': 'off',
    'no-jquery/no-size': 'error',
    'no-jquery/no-sizzle': 'off',
    'no-jquery/no-slide': 'off',
    'no-jquery/no-submit': 'error',
    'no-jquery/no-text': 'error',
    'no-jquery/no-toggle': 'off',
    'no-jquery/no-trigger': 'off',
    'no-jquery/no-trim': 'error',
    'no-jquery/no-val': 'error',
    'no-jquery/no-when': 'error',
    'no-jquery/no-wrap': 'off',
  },
});
