<?php

/**
 * @file
 */

/**
 * Implements hook_module_implements_alter().
 */
function navigation_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'page_top') {
    $group = $implementations['navigation'];
    unset($implementations['navigation']);
    $implementations['navigation'] = $group;
  }
  if ($hook == 'help') {
    // We take over the layout_builder hook_help().
    unset($implementations['layout_builder']);
  }
}
