/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.pathDetailsSummaries = {
    attach(context) {
      $(context).find('.path-form').drupalSetSummary(context => {
        const pathElement = document.querySelector('.js-form-item-path-0-alias input');
        const path = pathElement && pathElement.value;
        return path ? Drupal.t('Alias: @alias', {
          '@alias': path
        }) : Drupal.t('No alias');
      });
    }

  };
})(jQuery, Drupal);