/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function (_ref) {
  var deprecationError = _ref.deprecationError,
    deprecatedProperty = _ref.deprecatedProperty,
    behaviors = _ref.behaviors;
  var deprecatedFunction = function deprecatedFunction() {
    deprecationError({
      message: 'This function is deprecated for testing purposes.'
    });
  };
  var objectWithDeprecatedProperty = deprecatedProperty({
    target: {
      deprecatedProperty: 'Kitten'
    },
    deprecatedProperty: 'deprecatedProperty',
    message: 'This property is deprecated for testing purposes.'
  });
  behaviors.testDeprecations = {
    attach: function attach() {
      deprecatedFunction();
      var deprecatedProperty = objectWithDeprecatedProperty.deprecatedProperty;
    }
  };
})(Drupal);