<?php

/**
 * @file
 * Manage the entity system.
 *
 * The module is mostly an anchor point for configuration items owned by the
 * entity system.
 */

use Drupal\Core\Config\Entity\ConfigStorageController;

/**
 * Implements hook_field_attach_rename_bundle().
 */
function entity_field_attach_rename_bundle($entity_type, $bundle_old, $bundle_new) {
  $entity_info = entity_get_info('entity_display');

  // Rename entity displays.
  if ($bundle_old !== $bundle_new) {
    $ids = config_get_storage_names_with_prefix('entity.display.' . $entity_type . '.' . $bundle_old);
    foreach ($ids as $id) {
      $id = ConfigStorageController::getIDFromConfigName($id, $entity_info['config_prefix']);
      $display = entity_load('entity_display', $id);
      $new_id = $entity_type . '.' . $bundle_new . '.' . $display->viewMode;
      $display->id = $new_id;
      $display->bundle = $bundle_new;
      $display->save();
    }
  }
}

/**
 * Implements hook_field_attach_delete_bundle().
 */
function entity_field_attach_delete_bundle($entity_type, $bundle, $instances) {
  $entity_info = entity_get_info('entity_display');

  // Remove entity displays of the deleted bundle.
  $ids = config_get_storage_names_with_prefix('entity.display.' . $entity_type . '.' . $bundle);
  foreach ($ids as &$id) {
    $id = ConfigStorageController::getIDFromConfigName($id, $entity_info['config_prefix']);
  }
  entity_delete_multiple('entity_display', $ids);
}
