<?php

/**
 * @file
 * Contains hook implementations for testing HAL module.
 */

/**
 * Implements hook_hal_type_uri_alter().
 */
function hal_test_hal_type_uri_alter(&$uri, $context = []) {
  if (!empty($context['hal_test'])) {
    $uri = 'hal_test_type';
  }
}

/**
 * Implements hook_hal_relation_uri_alter().
 */
function hal_test_hal_relation_uri_alter(&$uri, $context = []) {
  if (!empty($context['hal_test'])) {
    $uri = 'hal_test_relation';
  }
}
