<?php

/**
 * @file
 * Helper module for entity cache tests.
 */

/**
 * Implements hook_watchdog().
 *
 * This hook is called during \Drupal\Core\Extension\ModuleHandler::install()
 * and since this hook implementation is invoked, we have to expect that this
 * module and dependent modules have been properly installed already. So we
 * expect to be able to retrieve the entity information that has been registered
 * by the required dependency module.
 *
 * @see EnableDisableTestCase::testEntityCache()
 */
function entity_cache_test_watchdog($log_entry) {
  if ($log_entry['type'] == 'system' && $log_entry['message'] == '%module module installed.') {
    $info = \Drupal::entityManager()->getDefinition('entity_cache_test');
    // Store the information in a system variable to analyze it later in the
    // test case.
    \Drupal::state()->set('entity_cache_test', $info);
  }
}
