/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.MediaLibrary = {
    currentSelection: [],
    onSelectMediaItem: function onSelectMediaItem(event) {
      event.preventDefault();
      var $input = $(event.currentTarget).closest('.js-click-to-select').find('.js-click-to-select-checkbox input');
      $input.prop('checked', !$input.prop('checked')).trigger('change');
    }
  };
})(jQuery, Drupal);