#!/bin/sh
find . -name "*~" -type f | xargs rm -f
find . -name "DEADJOE" -type f | xargs rm -f
find . -name "*" -type f | grep -v ".gif" | grep -v ".jpg" | xargs perl -wi -pe 's/\s+$/\n/'
find . -name "*" -type f | grep -v ".gif" | grep -v ".jpg" | xargs perl -wi -pe 's/\t/  /g'
