<?php

namespace Drupal\Composer\Plugin\Scaffold;

use Composer\IO\IOInterface;
use Composer\Util\Filesystem;
use Drupal\Composer\Plugin\Scaffold\Operations\ScaffoldResult;

/**
 * Generates the 'includes/locations.inc' file which defines location constants.
 *
 * Drupal and the webroot may be installed in various locations, and at runtime
 * it is not easy to determine these. Part of the difficulty is that Composer
 * can symlink packages in, and PHP's file location constants such as __DIR__
 * resolve symlinks.
 *
 * The authority on the location of packages is Composer, and the authority on
 * the location of the webroot is this scaffolding plugin. Therefore, we write
 * a PHP file which defines the locations as constants.
 *
 * @internal
 */
final class GenerateLocationsFile {

  /**
   * Generates the locations.inc file in Drupal core's 'includes' directory.
   *
   * @param \Composer\IO\IOInterface $io
   *   IOInterface to write to.
   * @param string $drupal_core_install_path
   *   The Composer install path of the drupal/core package.
   * @param string $drupal_root
   *   The location of the Drupal web root, that is, where this scaffolding
   *   plugin writes files such as 'index.php'.
   */
  public static function generateLocationsFile(IOInterface $io, $drupal_core_install_path, $drupal_root) {
    file_put_contents($drupal_core_install_path . '/includes/locations.inc', static::locationsContents($drupal_root));
  }

  /**
   * Builds the contents of the locations file.
   *
   * @param string $drupal_root
   *   The location of the Drupal web root.
   *
   * @return string
   *   Return the contents for the locations.inc.
   */
  public static function locationsContents($drupal_root) {
    return <<<EOF
    <?php

    /**
     * @file
     * Sets the location of Drupal root.
     *
     * This allows Drupal to find the Drupal web root.
     *
     * This file is included by bootstrap.inc, which is loaded by the Composer
     * autoloader. This allows it to be available as early as possible in
     * various circumstances.
     *
     * This file was generated by drupal-scaffold.
     *
     * @see composer.json
     */

    /**
     * Defines the root directory of the Drupal installation.
     */
    define('DRUPAL_ROOT', '{$drupal_root}');

    EOF;
  }

}
