<?php

/**
 * @file
 */

/**
 * Determines if an entity type is using an integer-based ID definition.
 *
 * @param string $entity_type_id
 *   The ID the represents the entity type.
 *
 * @return bool
 *   Returns TRUE if the entity type has an integer-based ID definition and
 *   FALSE otherwise.
 *
 * @deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. Use
 *   \Drupal\Core\Entity\EntityTypeInterface::hasIntegerId() instead.
 *
 * @see https://www.drupal.org/node/3566814
 */
function _comment_entity_uses_integer_id($entity_type_id) {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. Use \Drupal\Core\Entity\EntityTypeInterface::hasIntegerId() instead. See https://www.drupal.org/node/3566814', E_USER_DEPRECATED);
  return \Drupal::entityTypeManager()->getDefinition($entity_type_id)->hasIntegerId();
}
