<?php

/**
 * @file
 * Sets up the key value entity storage.
 */

/**
 * Implements hook_entity_type_alter().
 */
function keyvalue_test_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  if (isset($entity_types['config_test'])) {
    $entity_types['config_test']->setStorageClass('Drupal\Core\Entity\KeyValueStore\KeyValueConfigEntityStorage');
  }
  if (isset($entity_types['entity_test_label'])) {
    $entity_types['entity_test_label']->setStorageClass('Drupal\Core\Entity\KeyValueStore\KeyValueEntityStorage');
    $entity_keys = $entity_types['entity_test_label']->getKeys();
    $entity_types['entity_test_label']->set('entity_keys', $entity_keys + array('uuid' => 'uuid'));
  }
}
