<?php

/**
 * @file
 * Contains \Drupal\migrate_drupal\Tests\Table\d6\EventTimezones.
 *
 * THIS IS A GENERATED FILE. DO NOT EDIT.
 *
 * @see core/scripts/migrate-db.sh
 * @see https://www.drupal.org/sandbox/benjy/2405029
 */

namespace Drupal\migrate_drupal\Tests\Table\d6;

use Drupal\migrate_drupal\Tests\Dump\DrupalDumpBase;

/**
 * Generated file to represent the event_timezones table.
 */
class EventTimezones extends DrupalDumpBase {

  public function load() {
    $this->createTable("event_timezones", array(
      'primary key' => array(
        'timezone',
      ),
      'fields' => array(
        'timezone' => array(
          'type' => 'int',
          'not null' => TRUE,
          'length' => '11',
          'default' => '0',
        ),
        'name' => array(
          'type' => 'varchar',
          'not null' => TRUE,
          'length' => '255',
          'default' => '',
        ),
        'offset' => array(
          'type' => 'varchar',
          'not null' => TRUE,
          'length' => '100',
          'default' => '00:00:00',
        ),
        'offset_dst' => array(
          'type' => 'varchar',
          'not null' => TRUE,
          'length' => '100',
          'default' => '00:00:00',
        ),
        'dst_region' => array(
          'type' => 'int',
          'not null' => TRUE,
          'length' => '11',
          'default' => '0',
        ),
        'is_dst' => array(
          'type' => 'int',
          'not null' => TRUE,
          'length' => '11',
          'default' => '0',
        ),
      ),
    ));
    $this->database->insert("event_timezones")->fields(array(
      'timezone',
      'name',
      'offset',
      'offset_dst',
      'dst_region',
      'is_dst',
    ))
    ->values(array(
      'timezone' => '1',
      'name' => 'Africa/Addis Ababa',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '2',
      'name' => 'Africa/Algiers',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '3',
      'name' => 'Africa/Asmera',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '4',
      'name' => 'Africa/Bangui',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '5',
      'name' => 'Africa/Blantyre',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '6',
      'name' => 'Africa/Brazzaville',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '7',
      'name' => 'Africa/Bujumbura',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '8',
      'name' => 'Africa/Cairo',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '1',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '9',
      'name' => 'Africa/Ceuta',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '1',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '10',
      'name' => 'Africa/Dar es Salaam',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '11',
      'name' => 'Africa/Djibouti',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '12',
      'name' => 'Africa/Douala',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '13',
      'name' => 'Africa/Gaborone',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '14',
      'name' => 'Africa/Harare',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '15',
      'name' => 'Africa/Johannesburg',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '16',
      'name' => 'Africa/Kampala',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '17',
      'name' => 'Africa/Khartoum',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '18',
      'name' => 'Africa/Kigali',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '19',
      'name' => 'Africa/Kinshasa',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '20',
      'name' => 'Africa/Lagos',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '21',
      'name' => 'Africa/Libreville',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '22',
      'name' => 'Africa/Luanda',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '23',
      'name' => 'Africa/Lubumbashi',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '24',
      'name' => 'Africa/Lusaka',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '25',
      'name' => 'Africa/Malabo',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '26',
      'name' => 'Africa/Maputo',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '27',
      'name' => 'Africa/Maseru',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '28',
      'name' => 'Africa/Mbabane',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '29',
      'name' => 'Africa/Mogadishu',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '30',
      'name' => 'Africa/Nairobi',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '31',
      'name' => 'Africa/Ndjamena',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '32',
      'name' => 'Africa/Niamey',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '33',
      'name' => 'Africa/Porto-Novo',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '34',
      'name' => 'Africa/Tripoli',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '35',
      'name' => 'Africa/Tunis',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '36',
      'name' => 'Africa/Windhoek',
      'offset' => '02:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '2',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '37',
      'name' => 'America/Adak',
      'offset' => '-10:00:00',
      'offset_dst' => '-09:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '38',
      'name' => 'America/Anchorage',
      'offset' => '-09:00:00',
      'offset_dst' => '-08:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '39',
      'name' => 'America/Anguilla',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '40',
      'name' => 'America/Antigua',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '41',
      'name' => 'America/Araguaina',
      'offset' => '-02:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '17',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '42',
      'name' => 'America/Aruba',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '43',
      'name' => 'America/Asuncion',
      'offset' => '-03:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '20',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '44',
      'name' => 'America/Atka',
      'offset' => '-10:00:00',
      'offset_dst' => '-09:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '45',
      'name' => 'America/Barbados',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '46',
      'name' => 'America/Belem',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '47',
      'name' => 'America/Belize',
      'offset' => '-06:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '48',
      'name' => 'America/Boa Vista',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '49',
      'name' => 'America/Bogota',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '50',
      'name' => 'America/Boise',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '51',
      'name' => 'America/Buenos Aires',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '52',
      'name' => 'America/Cambridge Bay',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '53',
      'name' => 'America/Cancun',
      'offset' => '-06:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '54',
      'name' => 'America/Caracas',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '55',
      'name' => 'America/Catamarca',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '56',
      'name' => 'America/Cayenne',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '57',
      'name' => 'America/Cayman',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '58',
      'name' => 'America/Chicago',
      'offset' => '-06:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '59',
      'name' => 'America/Chihuahua',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '60',
      'name' => 'America/Cordoba',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '61',
      'name' => 'America/Costa Rica',
      'offset' => '-06:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '62',
      'name' => 'America/Cuiaba',
      'offset' => '-03:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '17',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '63',
      'name' => 'America/Curacao',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '64',
      'name' => 'America/Dawson',
      'offset' => '-08:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '65',
      'name' => 'America/Dawson Creek',
      'offset' => '-07:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '66',
      'name' => 'America/Denver',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '67',
      'name' => 'America/Detroit',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '68',
      'name' => 'America/Dominica',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '69',
      'name' => 'America/Edmonton',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '70',
      'name' => 'America/Eirunepe',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '71',
      'name' => 'America/El Salvador',
      'offset' => '-06:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '72',
      'name' => 'America/Ensenada',
      'offset' => '-08:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '73',
      'name' => 'America/Fort Wayne',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '74',
      'name' => 'America/Fortaleza',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '75',
      'name' => 'America/Glace Bay',
      'offset' => '-04:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '76',
      'name' => 'America/Godthab',
      'offset' => '-03:00:00',
      'offset_dst' => '-02:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '77',
      'name' => 'America/Goose Bay',
      'offset' => '-04:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '78',
      'name' => 'America/Grand Turk',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '16',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '79',
      'name' => 'America/Grenada',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '80',
      'name' => 'America/Guadeloupe',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '81',
      'name' => 'America/Guatemala',
      'offset' => '-06:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '82',
      'name' => 'America/Guayaquil',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '83',
      'name' => 'America/Guyana',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '84',
      'name' => 'America/Halifax',
      'offset' => '-04:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '85',
      'name' => 'America/Havana',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '16',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '86',
      'name' => 'America/Hermosillo',
      'offset' => '-07:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '87',
      'name' => 'America/Indiana/Indianapolis',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '88',
      'name' => 'America/Indiana/Knox',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '89',
      'name' => 'America/Indiana/Marengo',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '90',
      'name' => 'America/Indiana/Vevay',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '91',
      'name' => 'America/Indianapolis',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '92',
      'name' => 'America/Inuvik',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '93',
      'name' => 'America/Iqaluit',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '94',
      'name' => 'America/Jamaica',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '95',
      'name' => 'America/Jujuy',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '96',
      'name' => 'America/Juneau',
      'offset' => '-09:00:00',
      'offset_dst' => '-08:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '97',
      'name' => 'America/Kentucky/Louisville',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '98',
      'name' => 'America/Kentucky/Monticello',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '99',
      'name' => 'America/Knox IN',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '100',
      'name' => 'America/La Paz',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '101',
      'name' => 'America/Lima',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '102',
      'name' => 'America/Los Angeles',
      'offset' => '-08:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '103',
      'name' => 'America/Louisville',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '104',
      'name' => 'America/Maceio',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '105',
      'name' => 'America/Managua',
      'offset' => '-06:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '106',
      'name' => 'America/Manaus',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '107',
      'name' => 'America/Martinique',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '108',
      'name' => 'America/Mazatlan',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '109',
      'name' => 'America/Mendoza',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '110',
      'name' => 'America/Menominee',
      'offset' => '-06:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '111',
      'name' => 'America/Merida',
      'offset' => '-06:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '112',
      'name' => 'America/Mexico City',
      'offset' => '-06:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '113',
      'name' => 'America/Miquelon',
      'offset' => '-03:00:00',
      'offset_dst' => '-02:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '114',
      'name' => 'America/Monterrey',
      'offset' => '-06:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '115',
      'name' => 'America/Montevideo',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '116',
      'name' => 'America/Montreal',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '117',
      'name' => 'America/Montserrat',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '118',
      'name' => 'America/Nassau',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '119',
      'name' => 'America/New York',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '120',
      'name' => 'America/Nipigon',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '121',
      'name' => 'America/Nome',
      'offset' => '-09:00:00',
      'offset_dst' => '-08:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '122',
      'name' => 'America/Noronha',
      'offset' => '-02:00:00',
      'offset_dst' => '-02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '123',
      'name' => 'America/Panama',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '124',
      'name' => 'America/Pangnirtung',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '125',
      'name' => 'America/Paramaribo',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '126',
      'name' => 'America/Phoenix',
      'offset' => '-07:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '127',
      'name' => 'America/Port-au-Prince',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '128',
      'name' => 'America/Port of Spain',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '129',
      'name' => 'America/Porto Acre',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '130',
      'name' => 'America/Porto Velho',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '131',
      'name' => 'America/Puerto Rico',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '132',
      'name' => 'America/Rainy River',
      'offset' => '-06:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '133',
      'name' => 'America/Rankin Inlet',
      'offset' => '-06:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '134',
      'name' => 'America/Recife',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '135',
      'name' => 'America/Regina',
      'offset' => '-06:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '136',
      'name' => 'America/Rio Branco',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '137',
      'name' => 'America/Rosario',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '138',
      'name' => 'America/Santiago',
      'offset' => '-03:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '139',
      'name' => 'America/Santo Domingo',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '140',
      'name' => 'America/Sao Paulo',
      'offset' => '-02:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '141',
      'name' => 'America/Scoresbysund',
      'offset' => '-01:00:00',
      'offset_dst' => '00:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '142',
      'name' => 'America/Shiprock',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '143',
      'name' => 'America/St Johns',
      'offset' => '-03:30:00',
      'offset_dst' => '-02:30:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '144',
      'name' => 'America/St Kitts',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '145',
      'name' => 'America/St Lucia',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '146',
      'name' => 'America/St Thomas',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '147',
      'name' => 'America/St Vincent',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '148',
      'name' => 'America/Swift Current',
      'offset' => '-06:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '149',
      'name' => 'America/Tegucigalpa',
      'offset' => '-06:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '150',
      'name' => 'America/Thule',
      'offset' => '-04:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '151',
      'name' => 'America/Thunder Bay',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '152',
      'name' => 'America/Tijuana',
      'offset' => '-08:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '153',
      'name' => 'America/Tortola',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '154',
      'name' => 'America/Vancouver',
      'offset' => '-08:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '155',
      'name' => 'America/Virgin',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '156',
      'name' => 'America/Whitehorse',
      'offset' => '-08:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '157',
      'name' => 'America/Winnipeg',
      'offset' => '-06:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '158',
      'name' => 'America/Yakutat',
      'offset' => '-09:00:00',
      'offset_dst' => '-08:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '159',
      'name' => 'America/Yellowknife',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '160',
      'name' => 'Antarctica/Casey',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '161',
      'name' => 'Antarctica/Davis',
      'offset' => '07:00:00',
      'offset_dst' => '07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '162',
      'name' => 'Antarctica/DumontDUrville',
      'offset' => '10:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '163',
      'name' => 'Antarctica/Mawson',
      'offset' => '06:00:00',
      'offset_dst' => '06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '164',
      'name' => 'Antarctica/McMurdo',
      'offset' => '13:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '11',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '165',
      'name' => 'Antarctica/Palmer',
      'offset' => '-03:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '18',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '166',
      'name' => 'Antarctica/South Pole',
      'offset' => '13:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '11',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '167',
      'name' => 'Antarctica/Syowa',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '168',
      'name' => 'Antarctica/Vostok',
      'offset' => '06:00:00',
      'offset_dst' => '06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '169',
      'name' => 'Arctic/Longyearbyen',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '14',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '170',
      'name' => 'Asia/Aden',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '171',
      'name' => 'Asia/Almaty',
      'offset' => '06:00:00',
      'offset_dst' => '06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '172',
      'name' => 'Asia/Amman',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '8',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '173',
      'name' => 'Asia/Anadyr',
      'offset' => '12:00:00',
      'offset_dst' => '13:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '174',
      'name' => 'Asia/Aqtau',
      'offset' => '04:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '175',
      'name' => 'Asia/Aqtobe',
      'offset' => '05:00:00',
      'offset_dst' => '06:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '176',
      'name' => 'Asia/Ashgabat',
      'offset' => '05:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '177',
      'name' => 'Asia/Ashkhabad',
      'offset' => '05:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '178',
      'name' => 'Asia/Baghdad',
      'offset' => '03:00:00',
      'offset_dst' => '04:00:00',
      'dst_region' => '4',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '179',
      'name' => 'Asia/Bahrain',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '180',
      'name' => 'Asia/Baku',
      'offset' => '04:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '181',
      'name' => 'Asia/Bangkok',
      'offset' => '07:00:00',
      'offset_dst' => '07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '182',
      'name' => 'Asia/Beirut',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '6',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '183',
      'name' => 'Asia/Bishkek',
      'offset' => '05:00:00',
      'offset_dst' => '06:00:00',
      'dst_region' => '6',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '184',
      'name' => 'Asia/Brunei',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '185',
      'name' => 'Asia/Calcutta',
      'offset' => '05:30:00',
      'offset_dst' => '05:30:30',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '186',
      'name' => 'Asia/Chungking',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '187',
      'name' => 'Asia/Colombo',
      'offset' => '06:00:00',
      'offset_dst' => '06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '188',
      'name' => 'Asia/Dacca',
      'offset' => '06:00:00',
      'offset_dst' => '06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '189',
      'name' => 'Asia/Damascus',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '4',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '190',
      'name' => 'Asia/Dhaka',
      'offset' => '06:00:00',
      'offset_dst' => '06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '191',
      'name' => 'Asia/Dili',
      'offset' => '09:00:00',
      'offset_dst' => '09:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '192',
      'name' => 'Asia/Dubai',
      'offset' => '04:00:00',
      'offset_dst' => '04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '193',
      'name' => 'Asia/Dushanbe',
      'offset' => '05:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '194',
      'name' => 'Asia/Gaza',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '7',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '195',
      'name' => 'Asia/Harbin',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '196',
      'name' => 'Asia/Hong Kong',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '197',
      'name' => 'Asia/Hovd',
      'offset' => '07:00:00',
      'offset_dst' => '07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '198',
      'name' => 'Asia/Irkutsk',
      'offset' => '08:00:00',
      'offset_dst' => '09:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '199',
      'name' => 'Asia/Istanbul',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '200',
      'name' => 'Asia/Jakarta',
      'offset' => '07:00:00',
      'offset_dst' => '07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '201',
      'name' => 'Asia/Jayapura',
      'offset' => '09:00:00',
      'offset_dst' => '09:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '202',
      'name' => 'Asia/Jerusalem',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '5',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '203',
      'name' => 'Asia/Kabul',
      'offset' => '04:30:00',
      'offset_dst' => '04:30:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '204',
      'name' => 'Asia/Kamchatka',
      'offset' => '12:00:00',
      'offset_dst' => '13:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '205',
      'name' => 'Asia/Karachi',
      'offset' => '05:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '206',
      'name' => 'Asia/Kashgar',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '207',
      'name' => 'Asia/Katmandu',
      'offset' => '05:45:00',
      'offset_dst' => '05:45:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '208',
      'name' => 'Asia/Krasnoyarsk',
      'offset' => '07:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '209',
      'name' => 'Asia/Kuala Lumpur',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '210',
      'name' => 'Asia/Kuching',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '211',
      'name' => 'Asia/Kuwait',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '212',
      'name' => 'Asia/Macao',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '213',
      'name' => 'Asia/Magadan',
      'offset' => '11:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '214',
      'name' => 'Asia/Manila',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '215',
      'name' => 'Asia/Muscat',
      'offset' => '04:00:00',
      'offset_dst' => '04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '216',
      'name' => 'Asia/Nicosia',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '217',
      'name' => 'Asia/Novosibirsk',
      'offset' => '06:00:00',
      'offset_dst' => '07:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '218',
      'name' => 'Asia/Omsk',
      'offset' => '06:00:00',
      'offset_dst' => '07:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '219',
      'name' => 'Asia/Phnom Penh',
      'offset' => '07:00:00',
      'offset_dst' => '07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '220',
      'name' => 'Asia/Pyongyang',
      'offset' => '09:00:00',
      'offset_dst' => '09:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '221',
      'name' => 'Asia/Qatar',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '222',
      'name' => 'Asia/Rangoon',
      'offset' => '06:30:00',
      'offset_dst' => '06:30:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '223',
      'name' => 'Asia/Riyadh',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '224',
      'name' => 'Asia/Riyadh87',
      'offset' => '03:07:04',
      'offset_dst' => '03:07:04',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '225',
      'name' => 'Asia/Riyadh88',
      'offset' => '03:07:04',
      'offset_dst' => '03:07:04',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '226',
      'name' => 'Asia/Riyadh89',
      'offset' => '03:07:04',
      'offset_dst' => '03:07:04',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '227',
      'name' => 'Asia/Saigon',
      'offset' => '07:00:00',
      'offset_dst' => '07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '228',
      'name' => 'Asia/Samarkand',
      'offset' => '05:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '229',
      'name' => 'Asia/Seoul',
      'offset' => '09:00:00',
      'offset_dst' => '09:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '230',
      'name' => 'Asia/Shanghai',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '231',
      'name' => 'Asia/Singapore',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '232',
      'name' => 'Asia/Taipei',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '233',
      'name' => 'Asia/Tashkent',
      'offset' => '05:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '234',
      'name' => 'Asia/Tbilisi',
      'offset' => '04:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '235',
      'name' => 'Asia/Tehran',
      'offset' => '03:30:00',
      'offset_dst' => '04:30:00',
      'dst_region' => '8',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '236',
      'name' => 'Asia/Tel Aviv',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '5',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '237',
      'name' => 'Asia/Thimbu',
      'offset' => '06:00:00',
      'offset_dst' => '06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '238',
      'name' => 'Asia/Thimphu',
      'offset' => '06:00:00',
      'offset_dst' => '06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '239',
      'name' => 'Asia/Tokyo',
      'offset' => '09:00:00',
      'offset_dst' => '09:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '240',
      'name' => 'Asia/Ujung Pandang',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '241',
      'name' => 'Asia/Ulaanbaatar',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '242',
      'name' => 'Asia/Ulan Bator',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '243',
      'name' => 'Asia/Urumqi',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '244',
      'name' => 'Asia/Vientiane',
      'offset' => '07:00:00',
      'offset_dst' => '07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '245',
      'name' => 'Asia/Vladivostok',
      'offset' => '10:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '246',
      'name' => 'Asia/Yakutsk',
      'offset' => '09:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '247',
      'name' => 'Asia/Yekaterinburg',
      'offset' => '05:00:00',
      'offset_dst' => '06:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '248',
      'name' => 'Asia/Yerevan',
      'offset' => '04:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '3',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '249',
      'name' => 'Atlantic/Azores',
      'offset' => '-01:00:00',
      'offset_dst' => '00:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '250',
      'name' => 'Atlantic/Bermuda',
      'offset' => '-04:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '251',
      'name' => 'Atlantic/Canary',
      'offset' => '00:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '252',
      'name' => 'Atlantic/Cape Verde',
      'offset' => '-01:00:00',
      'offset_dst' => '-01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '253',
      'name' => 'Atlantic/Faeroe',
      'offset' => '00:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '254',
      'name' => 'Atlantic/Jan Mayen',
      'offset' => '-01:00:00',
      'offset_dst' => '-01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '255',
      'name' => 'Atlantic/Madeira',
      'offset' => '00:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '256',
      'name' => 'Atlantic/South Georgia',
      'offset' => '-02:00:00',
      'offset_dst' => '-02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '257',
      'name' => 'Atlantic/Stanley',
      'offset' => '-03:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '19',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '258',
      'name' => 'Australia/ACT',
      'offset' => '10:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '9',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '259',
      'name' => 'Australia/Adelaide',
      'offset' => '10:30:00',
      'offset_dst' => '09:30:00',
      'dst_region' => '9',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '260',
      'name' => 'Australia/Brisbane',
      'offset' => '10:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '261',
      'name' => 'Australia/Broken Hill',
      'offset' => '10:30:00',
      'offset_dst' => '09:30:00',
      'dst_region' => '9',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '262',
      'name' => 'Australia/Canberra',
      'offset' => '11:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '9',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '263',
      'name' => 'Australia/Darwin',
      'offset' => '09:30:00',
      'offset_dst' => '09:30:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '264',
      'name' => 'Australia/Hobart',
      'offset' => '11:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '10',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '265',
      'name' => 'Australia/LHI',
      'offset' => '11:00:00',
      'offset_dst' => '10:30:00',
      'dst_region' => '9',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '266',
      'name' => 'Australia/Lindeman',
      'offset' => '10:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '267',
      'name' => 'Australia/Lord Howe',
      'offset' => '11:00:00',
      'offset_dst' => '10:30:00',
      'dst_region' => '9',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '268',
      'name' => 'Australia/Melbourne',
      'offset' => '10:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '10',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '269',
      'name' => 'Australia/NSW',
      'offset' => '10:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '9',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '270',
      'name' => 'Australia/North',
      'offset' => '09:30:00',
      'offset_dst' => '09:30:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '271',
      'name' => 'Australia/Perth',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '272',
      'name' => 'Australia/Queensland',
      'offset' => '10:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '273',
      'name' => 'Australia/South',
      'offset' => '10:30:00',
      'offset_dst' => '09:30:00',
      'dst_region' => '9',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '274',
      'name' => 'Australia/Sydney',
      'offset' => '10:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '10',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '275',
      'name' => 'Australia/Tasmania',
      'offset' => '10:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '9',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '276',
      'name' => 'Australia/Victoria',
      'offset' => '10:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '9',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '277',
      'name' => 'Australia/West',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '278',
      'name' => 'Australia/Yancowinna',
      'offset' => '10:30:00',
      'offset_dst' => '09:30:00',
      'dst_region' => '10',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '279',
      'name' => 'Brazil/Acre',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '280',
      'name' => 'Brazil/DeNoronha',
      'offset' => '-02:00:00',
      'offset_dst' => '-02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '281',
      'name' => 'Brazil/East',
      'offset' => '-02:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '17',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '282',
      'name' => 'Brazil/West',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '285',
      'name' => 'Canada/Atlantic',
      'offset' => '-04:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '286',
      'name' => 'Canada/Central',
      'offset' => '-06:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '287',
      'name' => 'Canada/Central-Saskatchewan',
      'offset' => '-06:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '288',
      'name' => 'Canada/Eastern',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '289',
      'name' => 'Canada/Mountain',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '290',
      'name' => 'Canada/Newfoundland',
      'offset' => '-03:30:00',
      'offset_dst' => '-02:30:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '291',
      'name' => 'Canada/Pacific',
      'offset' => '-08:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '292',
      'name' => 'Canada/Saskatchewan',
      'offset' => '-06:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '293',
      'name' => 'Canada/Yukon',
      'offset' => '-08:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '294',
      'name' => 'Chile/Continental',
      'offset' => '-03:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '18',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '295',
      'name' => 'Chile/EasterIsland',
      'offset' => '-05:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '18',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '296',
      'name' => 'Cuba',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '16',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '298',
      'name' => 'EST',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '300',
      'name' => 'Egypt',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '1',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '301',
      'name' => 'Eire',
      'offset' => '00:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '302',
      'name' => 'Etc/GMT-1',
      'offset' => '-01:00:00',
      'offset_dst' => '-01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '303',
      'name' => 'Etc/GMT-10',
      'offset' => '-10:00:00',
      'offset_dst' => '-10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '304',
      'name' => 'Etc/GMT-11',
      'offset' => '-11:00:00',
      'offset_dst' => '-11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '305',
      'name' => 'Etc/GMT-12',
      'offset' => '-12:00:00',
      'offset_dst' => '-12:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '306',
      'name' => 'Etc/GMT-2',
      'offset' => '-02:00:00',
      'offset_dst' => '-02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '307',
      'name' => 'Etc/GMT-3',
      'offset' => '-03:00:00',
      'offset_dst' => '-03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '308',
      'name' => 'Etc/GMT-4',
      'offset' => '-04:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '309',
      'name' => 'Etc/GMT-5',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '310',
      'name' => 'Etc/GMT-6',
      'offset' => '-06:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '311',
      'name' => 'Etc/GMT-7',
      'offset' => '-07:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '312',
      'name' => 'Etc/GMT-8',
      'offset' => '-08:00:00',
      'offset_dst' => '-08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '313',
      'name' => 'Etc/GMT-9',
      'offset' => '-09:00:00',
      'offset_dst' => '-09:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '314',
      'name' => 'Etc/GMT+1',
      'offset' => '01:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '315',
      'name' => 'Etc/GMT+10',
      'offset' => '10:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '316',
      'name' => 'Etc/GMT+11',
      'offset' => '11:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '317',
      'name' => 'Etc/GMT+12',
      'offset' => '12:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '318',
      'name' => 'Etc/GMT+13',
      'offset' => '13:00:00',
      'offset_dst' => '13:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '319',
      'name' => 'Etc/GMT+14',
      'offset' => '14:00:00',
      'offset_dst' => '14:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '320',
      'name' => 'Etc/GMT+2',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '321',
      'name' => 'Etc/GMT+3',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '322',
      'name' => 'Etc/GMT+4',
      'offset' => '04:00:00',
      'offset_dst' => '04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '323',
      'name' => 'Etc/GMT+5',
      'offset' => '05:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '324',
      'name' => 'Etc/GMT+6',
      'offset' => '06:00:00',
      'offset_dst' => '06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '325',
      'name' => 'Etc/GMT+7',
      'offset' => '07:00:00',
      'offset_dst' => '07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '326',
      'name' => 'Etc/GMT+8',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '327',
      'name' => 'Etc/GMT+9',
      'offset' => '09:00:00',
      'offset_dst' => '09:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '328',
      'name' => 'Europe/Amsterdam',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '329',
      'name' => 'Europe/Andorra',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '330',
      'name' => 'Europe/Athens',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '331',
      'name' => 'Europe/Belfast',
      'offset' => '00:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '332',
      'name' => 'Europe/Belgrade',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '333',
      'name' => 'Europe/Berlin',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '334',
      'name' => 'Europe/Bratislava',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '335',
      'name' => 'Europe/Brussels',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '336',
      'name' => 'Europe/Bucharest',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '337',
      'name' => 'Europe/Budapest',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '338',
      'name' => 'Europe/Chisinau',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '339',
      'name' => 'Europe/Copenhagen',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '340',
      'name' => 'Europe/Dublin',
      'offset' => '00:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '341',
      'name' => 'Europe/Gibraltar',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '342',
      'name' => 'Europe/Helsinki',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '343',
      'name' => 'Europe/Istanbul',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '344',
      'name' => 'Europe/Kaliningrad',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '345',
      'name' => 'Europe/Kiev',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '346',
      'name' => 'Europe/Lisbon',
      'offset' => '00:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '347',
      'name' => 'Europe/Ljubljana',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '348',
      'name' => 'Europe/London',
      'offset' => '00:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '349',
      'name' => 'Europe/Luxembourg',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '350',
      'name' => 'Europe/Madrid',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '351',
      'name' => 'Europe/Malta',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '352',
      'name' => 'Europe/Minsk',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '353',
      'name' => 'Europe/Monaco',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '354',
      'name' => 'Europe/Moscow',
      'offset' => '03:00:00',
      'offset_dst' => '04:00:00',
      'dst_region' => '14',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '355',
      'name' => 'Europe/Nicosia',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '356',
      'name' => 'Europe/Oslo',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '357',
      'name' => 'Europe/Paris',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '358',
      'name' => 'Europe/Prague',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '359',
      'name' => 'Europe/Riga',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '360',
      'name' => 'Europe/Rome',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '361',
      'name' => 'Europe/Samara',
      'offset' => '04:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '362',
      'name' => 'Europe/San Marino',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '363',
      'name' => 'Europe/Sarajevo',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '364',
      'name' => 'Europe/Simferopol',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '365',
      'name' => 'Europe/Skopje',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '366',
      'name' => 'Europe/Sofia',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '367',
      'name' => 'Europe/Stockholm',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '368',
      'name' => 'Europe/Tallinn',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '369',
      'name' => 'Europe/Tirane',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '370',
      'name' => 'Europe/Tiraspol',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '371',
      'name' => 'Europe/Uzhgorod',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '372',
      'name' => 'Europe/Vaduz',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '373',
      'name' => 'Europe/Vatican',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '374',
      'name' => 'Europe/Vienna',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '375',
      'name' => 'Europe/Vilnius',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '376',
      'name' => 'Europe/Warsaw',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '377',
      'name' => 'Europe/Zagreb',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '378',
      'name' => 'Europe/Zaporozhye',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '379',
      'name' => 'Europe/Zurich',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '380',
      'name' => 'GB',
      'offset' => '00:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '381',
      'name' => 'GB-Eire',
      'offset' => '00:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '383',
      'name' => 'Hongkong',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '384',
      'name' => 'Indian/Antananarivo',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '385',
      'name' => 'Indian/Chagos',
      'offset' => '05:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '386',
      'name' => 'Indian/Christmas',
      'offset' => '07:00:00',
      'offset_dst' => '07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '387',
      'name' => 'Indian/Cocos',
      'offset' => '06:30:00',
      'offset_dst' => '06:30:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '388',
      'name' => 'Indian/Comoro',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '389',
      'name' => 'Indian/Kerguelen',
      'offset' => '05:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '390',
      'name' => 'Indian/Mahe',
      'offset' => '04:00:00',
      'offset_dst' => '04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '391',
      'name' => 'Indian/Maldives',
      'offset' => '05:00:00',
      'offset_dst' => '05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '392',
      'name' => 'Indian/Mauritius',
      'offset' => '04:00:00',
      'offset_dst' => '04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '393',
      'name' => 'Indian/Mayotte',
      'offset' => '03:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '394',
      'name' => 'Indian/Reunion',
      'offset' => '04:00:00',
      'offset_dst' => '04:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '395',
      'name' => 'Iran',
      'offset' => '03:30:00',
      'offset_dst' => '04:30:00',
      'dst_region' => '8',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '396',
      'name' => 'Israel',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '5',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '397',
      'name' => 'Jamaica',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '398',
      'name' => 'Japan',
      'offset' => '09:00:00',
      'offset_dst' => '09:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '399',
      'name' => 'Kwajalein',
      'offset' => '12:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '400',
      'name' => 'Libya',
      'offset' => '02:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '404',
      'name' => 'Mexico/BajaNorte',
      'offset' => '-08:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '405',
      'name' => 'Mexico/BajaSur',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '406',
      'name' => 'Mexico/General',
      'offset' => '-06:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '407',
      'name' => 'Mideast/Riyadh87',
      'offset' => '03:07:04',
      'offset_dst' => '03:07:04',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '408',
      'name' => 'Mideast/Riyadh88',
      'offset' => '03:07:04',
      'offset_dst' => '03:07:04',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '409',
      'name' => 'Mideast/Riyadh89',
      'offset' => '03:07:04',
      'offset_dst' => '03:07:04',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '410',
      'name' => 'NZ',
      'offset' => '13:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '11',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '412',
      'name' => 'Navajo',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '415',
      'name' => 'Pacific/Apia',
      'offset' => '-11:00:00',
      'offset_dst' => '-11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '416',
      'name' => 'Pacific/Auckland',
      'offset' => '13:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '417',
      'name' => 'Pacific/Chatham',
      'offset' => '13:45:00',
      'offset_dst' => '12:45:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '418',
      'name' => 'Pacific/Easter',
      'offset' => '-05:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '419',
      'name' => 'Pacific/Efate',
      'offset' => '11:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '420',
      'name' => 'Pacific/Enderbury',
      'offset' => '13:00:00',
      'offset_dst' => '13:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '421',
      'name' => 'Pacific/Fakaofo',
      'offset' => '-10:00:00',
      'offset_dst' => '-10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '422',
      'name' => 'Pacific/Fiji',
      'offset' => '12:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '423',
      'name' => 'Pacific/Funafuti',
      'offset' => '12:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '424',
      'name' => 'Pacific/Galapagos',
      'offset' => '-06:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '425',
      'name' => 'Pacific/Gambier',
      'offset' => '-09:00:00',
      'offset_dst' => '-09:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '426',
      'name' => 'Pacific/Guadalcanal',
      'offset' => '11:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '427',
      'name' => 'Pacific/Guam',
      'offset' => '10:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '428',
      'name' => 'Pacific/Honolulu',
      'offset' => '-10:00:00',
      'offset_dst' => '-10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '429',
      'name' => 'Pacific/Johnston',
      'offset' => '-10:00:00',
      'offset_dst' => '-10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '430',
      'name' => 'Pacific/Kiritimati',
      'offset' => '14:00:00',
      'offset_dst' => '14:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '431',
      'name' => 'Pacific/Kosrae',
      'offset' => '11:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '432',
      'name' => 'Pacific/Kwajalein',
      'offset' => '12:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '433',
      'name' => 'Pacific/Majuro',
      'offset' => '12:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '434',
      'name' => 'Pacific/Marquesas',
      'offset' => '-09:30:00',
      'offset_dst' => '-09:30:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '435',
      'name' => 'Pacific/Midway',
      'offset' => '-11:00:00',
      'offset_dst' => '-11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '436',
      'name' => 'Pacific/Nauru',
      'offset' => '12:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '437',
      'name' => 'Pacific/Niue',
      'offset' => '-11:00:00',
      'offset_dst' => '-11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '438',
      'name' => 'Pacific/Norfolk',
      'offset' => '11:30:00',
      'offset_dst' => '11:30:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '439',
      'name' => 'Pacific/Noumea',
      'offset' => '11:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '440',
      'name' => 'Pacific/Pago Pago',
      'offset' => '-11:00:00',
      'offset_dst' => '-11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '441',
      'name' => 'Pacific/Palau',
      'offset' => '09:00:00',
      'offset_dst' => '09:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '442',
      'name' => 'Pacific/Pitcairn',
      'offset' => '-08:00:00',
      'offset_dst' => '-08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '443',
      'name' => 'Pacific/Ponape',
      'offset' => '11:00:00',
      'offset_dst' => '11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '444',
      'name' => 'Pacific/Port Moresby',
      'offset' => '10:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '445',
      'name' => 'Pacific/Rarotonga',
      'offset' => '-10:00:00',
      'offset_dst' => '-10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '446',
      'name' => 'Pacific/Saipan',
      'offset' => '10:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '447',
      'name' => 'Pacific/Samoa',
      'offset' => '-11:00:00',
      'offset_dst' => '-11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '448',
      'name' => 'Pacific/Tahiti',
      'offset' => '-10:00:00',
      'offset_dst' => '-10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '449',
      'name' => 'Pacific/Tarawa',
      'offset' => '12:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '450',
      'name' => 'Pacific/Tongatapu',
      'offset' => '13:00:00',
      'offset_dst' => '13:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '451',
      'name' => 'Pacific/Truk',
      'offset' => '10:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '452',
      'name' => 'Pacific/Wake',
      'offset' => '12:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '453',
      'name' => 'Pacific/Wallis',
      'offset' => '12:00:00',
      'offset_dst' => '12:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '454',
      'name' => 'Pacific/Yap',
      'offset' => '10:00:00',
      'offset_dst' => '10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '455',
      'name' => 'Poland',
      'offset' => '01:00:00',
      'offset_dst' => '02:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '456',
      'name' => 'Portugal',
      'offset' => '00:00:00',
      'offset_dst' => '01:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '459',
      'name' => 'Singapore',
      'offset' => '08:00:00',
      'offset_dst' => '08:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '473',
      'name' => 'Turkey',
      'offset' => '02:00:00',
      'offset_dst' => '03:00:00',
      'dst_region' => '13',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '474',
      'name' => 'US/Alaska',
      'offset' => '-09:00:00',
      'offset_dst' => '-08:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '475',
      'name' => 'US/Aleutian',
      'offset' => '-10:00:00',
      'offset_dst' => '-09:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '476',
      'name' => 'US/Arizona',
      'offset' => '-07:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '477',
      'name' => 'US/Central',
      'offset' => '-06:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '478',
      'name' => 'US/East-Indiana',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '479',
      'name' => 'US/Eastern',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '480',
      'name' => 'US/Hawaii',
      'offset' => '-10:00:00',
      'offset_dst' => '-10:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '481',
      'name' => 'US/Indiana-Starke',
      'offset' => '-05:00:00',
      'offset_dst' => '-05:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '482',
      'name' => 'US/Michigan',
      'offset' => '-05:00:00',
      'offset_dst' => '-04:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '483',
      'name' => 'US/Mountain',
      'offset' => '-07:00:00',
      'offset_dst' => '-06:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '484',
      'name' => 'US/Pacific',
      'offset' => '-08:00:00',
      'offset_dst' => '-07:00:00',
      'dst_region' => '15',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '485',
      'name' => 'US/Samoa',
      'offset' => '-11:00:00',
      'offset_dst' => '-11:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '486',
      'name' => 'Pacific/French Polynesia-Marquesas Islands',
      'offset' => '-09:30:00',
      'offset_dst' => '-09:30:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->values(array(
      'timezone' => '487',
      'name' => 'Etc/GMT',
      'offset' => '00:00:00',
      'offset_dst' => '00:00:00',
      'dst_region' => '0',
      'is_dst' => '0',
    ))->execute();
  }

}
#6b7541b69fbd9ffb83e93348c4ba479e
