drupal.settings_tray:
  version: VERSION
  js:
    js/settings_tray.js: {}
  css:
    component:
      css/settings_tray.module.css: {}
      css/settings_tray.motion.css: {}
      css/settings_tray.toolbar.css: {}
    theme:
      css/settings_tray.theme.css: {}
  dependencies:
    - core/jquery
    - core/drupal
    - core/once
    - core/drupal.ajax
  after:
    - core/drupal.dialog
