#!/usr/bin/env php
<?php

/**
 * @file
 * Provides CLI commands for Drupal.
 */

use Drupal\Core\Command\GenerateTheme;
use Drupal\Core\Command\QuickStartCommand;
use Drupal\Core\Command\InstallCommand;
use Drupal\Core\Command\ServerCommand;
use Drupal\Core\Recipe\RecipeCommand;
use Symfony\Component\Console\Application;

if (PHP_SAPI !== 'cli') {
  return;
}

$classloader = require_once __DIR__ . '/../../autoload.php';

$application = new Application('drupal', \Drupal::VERSION);

$application->add(new QuickStartCommand());
$application->add(new InstallCommand($classloader));
$application->add(new ServerCommand($classloader));
$application->add(new GenerateTheme());
$application->add(new RecipeCommand($classloader));

$application->run();
