<?php

/**
 * @file
 * Helper module for Views tests.
 */

use Drupal\views\View;

/**
 * Implements hook_permission().
 */
function views_test_data_permission() {
  return array(
    'views_test test permission' => array(
      'title' => t('Test permission'),
      'description' => t('views_test test permission'),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function views_test_data_views_api() {
  return array(
    'api' => 3.0,
    'template path' => drupal_get_path('module', 'views_test_data') . '/templates',
  );
}

/**
 * Implements hook_views_data().
 */
function views_test_data_views_data() {
  return variable_get('views_test_views_data', array());
}

function views_test_data_test_static_access_callback($access) {
  return $access;
}

function views_test_data_test_dynamic_access_callback($access, $argument1, $argument2) {
  return $access && $argument1 == variable_get('test_dynamic_access_argument1', NULL) && $argument2 == variable_get('test_dynamic_access_argument2', NULL);
}

/**
 * Implements hook_views_pre_render().
 */
function views_test_data_views_pre_render(&$view) {
  if ($view->name == 'test_cache_header_storage') {
    drupal_add_js(drupal_get_path('module', 'views_test') . '/views_cache.test.js');
    drupal_add_css(drupal_get_path('module', 'views_test') . '/views_cache.test.css');
    $view->pre_render_called = TRUE;
  }
}

/**
 * Implements hook_views_post_build().
 */
function views_test_data_views_post_build(View &$view) {
  if ($view->name == 'test_page_display') {
    if ($view->current_display == 'page_1') {
      $view->build_info['denied'] = TRUE;
    }
    elseif ($view->current_display == 'page_2') {
      $view->build_info['fail'] = TRUE;
    }
  }
}
